(()=>{
'use strict';
const $=id=>document.getElementById(id),c=$('gameCanvas'),x=c.getContext('2d');
const W=1440,H=760,G=575,L=[360,720,1080],SAVE='DINO_LEGENDS_V22';
const skins=[
 ['Rookie Rex','🦖',0],['Neon Rex','🤖',2500],['Ember Rex','🔥',5000],['Frost Rex','❄️',7500],['Cyber Raptor','⚡',10000],['Jungle King','🌿',15000],['Crystal Rex','💎',22000],['Shadow Rex','🌑',30000],['Solar Rex','☀️',40000],['Galaxy Rex','🌌',60000],['Mecha Titan','🦾',90000],['Void Emperor','👑',150000]
];
const worlds=[['Ancient Jungle',0,1],['Volcanic Wastes',5000,1.12],['Frost Realm',15000,.94],['Sky Ruins',30000,1.05],['Void Realm',60000,1.2]];
const upgrades=[['HEALTH','❤️','Max HP +1',800],['ENERGY CORE','⚡','Max energy +20',1200],['DASH ENGINE','💨','Dash costs 5 less',1600],['COMBO AMP','🔥','Combo score +12%',2200],['GEM MAGNET','🧲','More gems from runs',2800],['PARRY MATRIX','🛡️','Parry window +0.10s',3500],['RAGE CORE','☄️','Rage gains +20%',4500],['LUCK','🍀','Rare events appear more',6000]];
const missions=[['Combo Master','Reach x10 combo',10],['Gem Hunter','Collect 25 gems',25],['Air Ace','Defeat 15 airborne foes',15],['Guardian Slayer','Defeat 3 guardians',3],['Distance Runner','Survive 120 seconds',120],['Elite Hunter','Defeat 20 elites',20],['Perfect Timing','Land 10 parries',10],['World Traveler','Unlock 3 worlds',3]];
let s=(()=>{try{return JSON.parse(localStorage.getItem(SAVE))||null}catch{return null}})()||{gems:2500,best:0,skin:0,owned:[0],up:{},world:0,mission:{},stats:{gems:0,air:0,boss:0,time:0,elite:0,parry:0,runs:0}};
function save(){localStorage.setItem(SAVE,JSON.stringify(s))}
let run=false,pause=false,t=0,last=0,score=0,rg=0,hp=3,maxHp=3,energy=120,maxEnergy=120,rage=0,combo=1,peak=1,world=0,spawn=.5,boss=null,shake=0,objs=[],parts=[],texts=[];
function upgrades(){return Object.values(s.up).reduce((a,b)=>a+b,0)}
function has(i){return !!s.up[i]}
function maxHealth(){return 3+(has(0)?s.up[0]:0)}
function energyMax(){return 100+(has(1)?20*s.up[1]:0)}
function dashCost(){return Math.max(15,35-(has(2)?5*s.up[2]:0))}
function comboMult(){return 1+(has(3)?.12*s.up[3]:0)}
function gemMult(){return 1+(has(4)?.25*s.up[4]:0)}
function parryWindow(){return .32+(has(5)?.1*s.up[5]:0)}
function rageGain(){return 1+(has(6)?.2*s.up[6]:0)}
function panel(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));document.querySelectorAll('.panel').forEach(v=>v.classList.toggle('active',v.id===id))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>panel(b.dataset.panel));
function renderMeta(){
 const skin=$('skins');if(skin)skin.innerHTML=`<div class="heading"><div><small>CUSTOMIZATION</small><h2>SKIN FORGE</h2></div><b>${s.gems.toLocaleString()} GEMS</b></div><div class="grid">${skins.map((q,i)=>`<article class="item skinCard ${s.skin===i?'selected':''}"><div class="icon skinIcon">${q[1]}</div><h3>${q[0]}</h3><small>${i===0?'STARTER':i<4?'RARE':i<8?'EPIC':i<11?'LEGENDARY':'MYTHIC'}</small><p>${i===0?'Balanced starter.':'A unique visual identity with special trail effects.'}</p><footer><span class="price">${s.owned.includes(i)?(s.skin===i?'EQUIPPED':'OWNED'):q[2].toLocaleString()+' GEMS'}</span><button class="action skinBtn" data-skin="${i}" ${s.owned.includes(i)?'':' '+(s.gems<q[2]?'disabled':'')}>${s.owned.includes(i)?(s.skin===i?'EQUIPPED':'EQUIP'):'UNLOCK'}</button></footer></article>`).join('')}</div>`;
 const ab=$('abilities');if(ab)ab.innerHTML=`<div class="heading"><div><small>PROGRESSION</small><h2>UPGRADE LAB</h2></div><b>${upgrades()} UPGRADES</b></div><div class="grid">${upgradesList()}</div>`;
 const mi=$('missions');if(mi)mi.innerHTML=`<div class="heading"><div><small>DAILY + LIFETIME</small><h2>MISSIONS</h2></div></div>${missions.map((m,i)=>{const v=missionValue(i),done=v>=m[2],reward=(i+1)*750;return `<div class="mission"><span><b>${m[0]}</b><small>${m[1]} · ${Math.min(v,m[2])}/${m[2]}</small></span><b>${done?'CLAIMED':'+'+reward+' GEMS'}</b></div>`}).join('')}`;
 const wo=$('worlds');if(wo)wo.innerHTML=`<div class="heading"><div><small>EXPEDITION MAP</small><h2>WORLDS</h2></div></div><div class="grid">${worlds.map((w,i)=>`<article class="item ${s.world>=i?'':'locked'}"><div class="icon">${['🌴','🌋','❄️','🏛️','🌌'][i]}</div><h3>${w[0]}</h3><small>${s.world>=i?'UNLOCKED':'REQUIRES '+w[1].toLocaleString()+' BEST SCORE'}</small><p>Speed modifier ×${w[2].toFixed(2)}. New hazards and enemy patterns.</p><footer><button class="action worldBtn" data-world="${i}" ${s.world>=i?'':'disabled'}>${world===i?'ACTIVE':'ENTER'}</button></footer></article>`).join('')}</div>`;
 document.querySelectorAll('.skinBtn').forEach(b=>b.onclick=()=>buySkin(+b.dataset.skin));document.querySelectorAll('.upgradeBtn').forEach(b=>b.onclick=()=>buyUpgrade(+b.dataset.up));document.querySelectorAll('.worldBtn').forEach(b=>b.onclick=()=>{world=+b.dataset.world;renderMeta()});
}
function upgradesList(){return upgrades.map((u,i)=>{const lv=s.up[i]||0,cost=Math.floor(u[3]*Math.pow(1.65,lv));return `<article class="item"><div class="icon">${u[1]}</div><h3>${u[0]}</h3><small>LEVEL ${lv}/5</small><p>${u[2]}</p><footer><span class="price">${lv>=5?'MAX':cost.toLocaleString()+' GEMS'}</span><button class="action upgradeBtn" data-up="${i}" ${lv>=5||s.gems<cost?'disabled':''}>${lv>=5?'MAX':'UPGRADE'}</button></footer></article>`}).join('')}
function buySkin(i){if(s.owned.includes(i)){s.skin=i;save();renderMeta();return}if(s.gems>=skins[i][2]){s.gems-=skins[i][2];s.owned.push(i);s.skin=i;save();renderMeta();hud()}}
function buyUpgrade(i){const lv=s.up[i]||0;if(lv>=5)return;const cost=Math.floor(upgrades[i][3]*Math.pow(1.65,lv));if(s.gems>=cost){s.gems-=cost;s.up[i]=lv+1;save();renderMeta();hud()}}
function missionValue(i){const a=s.stats;return [peak, a.gems, a.air, a.boss, Math.floor(a.time), a.elite, a.parry, s.world+1][i]}
function missionCheck(){missions.forEach((m,i)=>{if(!s.mission[i]&&missionValue(i)>=m[2]){s.mission[i]=1;s.gems+=(i+1)*750;save();say(720,180,'MISSION COMPLETE +'+(i+1)*750,'gold')}});renderMeta()}
function resize(){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.7);c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);x.setTransform(c.width/W,0,0,c.height/H,0,0)}addEventListener('resize',resize);resize();
function reset(){run=true;pause=false;t=score=rg=0;maxHp=maxHealth();hp=maxHp;maxEnergy=energyMax();energy=maxEnergy;rage=0;combo=1;peak=1;spawn=.4;boss=null;objs=[];parts=[];texts=[];s.stats.runs++;last=performance.now();$('startScreen')?.classList.add('hidden');$('gameOverScreen')?.classList.add('hidden');save();requestAnimationFrame(loop)}
function end(){if(!run)return;run=false;const final=Math.floor(score);s.best=Math.max(s.best,final);s.gems+=Math.floor(rg*gemMult());s.stats.time+=t;s.stats.gems+=Math.floor(rg);if(final>=worlds[Math.min(worlds.length-1,s.world+1)][1])s.world=Math.min(worlds.length-1,s.world+1);save();missionCheck();$('finalScore').textContent=final.toLocaleString();$('finalStats').textContent=`WORLD ${worlds[world][0]} · PEAK x${peak.toFixed(1)} · +${Math.floor(rg*gemMult())} GEMS`;$('gameOverScreen').classList.remove('hidden');hud()}
function act(a){if(!run||pause)return;if(a==='left')P.l=Math.max(0,P.l-1);else if(a==='right')P.l=Math.min(2,P.l+1);else if(a==='jump'&&P.j<2){P.v=P.j?-780:-940;P.j++;burst(P.x,G-P.y,8,'cyan')}else if(a==='attack')P.a=.22;else if(a==='dash'&&energy>=dashCost()){energy-=dashCost();P.d=.38;P.inv=.5;burst(P.x,G-P.y,20,'gold');shake=6}else if(a==='parry'&&energy>=20){energy-=20;P.par=parryWindow()}else if(a==='rage'&&rage>=100){rage=0;score+=2200*combo;combo=Math.min(30,combo+3);burst(P.x,G-P.y,30,'violet')}}
const P={l:1,x:720,y:0,v:0,j:0,a:0,d:0,par:0,inv:0};document.querySelectorAll('[data-action]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();act(b.dataset.action)});addEventListener('keydown',e=>{if(['Space','ArrowLeft','ArrowRight','ArrowUp'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft'||e.code==='KeyA')act('left');else if(e.code==='ArrowRight'||e.code==='KeyD')act('right');else if(e.code==='Space'||e.code==='ArrowUp')act('jump');else if(e.code==='KeyF')act('attack');else if(e.code.startsWith('Shift'))act('dash');else if(e.code==='KeyS')act('parry');else if(e.code==='KeyR')act('rage');else if(e.code==='Escape'&&run){pause=!pause;$('pauseScreen').classList.toggle('hidden',!pause);if(!pause)last=performance.now()}else if(e.code==='Enter'&&!run)reset()});
$('startButton').onclick=reset;$('restartButton').onclick=reset;$('resumeButton').onclick=()=>{pause=false;$('pauseScreen').classList.add('hidden');last=performance.now()};
function spawn(type,lane,x0=W+100){const D={rock:[70,60,G-30],spike:[68,42,G-18],enemy:[68,75,G-38],elite:[82,88,G-45],air:[72,48,390],gem:[30,30,G-120],meteor:[90,50,330],crystal:[38,50,G-160]}[type];if(D)objs.push({type,lane,x:x0,w:D[0],y:D[2],hp:type==='elite'?2:1,cool:0,dead:0})}
function pattern(){const r=Math.random(),l=Math.floor(Math.random()*3);if(t<6){spawn(r<.7?'rock':'gem',l);return}const chaos=has(7)?s.up[7]*.03:0;if(r<.12+chaos){spawn('meteor',l);spawn('crystal',(l+1)%3,W+230)}else if(r<.28){spawn('enemy',l);spawn('air',(l+1)%3,W+260)}else if(r<.44){spawn('rock',l);spawn('spike',(l+1)%3,W+210)}else if(r<.58){spawn('elite',l)}else if(r<.72){spawn('air',l);spawn('gem',(l+2)%3,W+190)}else{spawn('spike',l);spawn('rock',(l+2)%3,W+250)}}
function hit(){if(P.inv)return;if(P.par){score+=650*combo;combo=Math.min(30,combo+1.7);peak=Math.max(peak,combo);rage=Math.min(100,rage+8*rageGain());P.par=0;s.stats.parry++;say(P.x,G-100,'PERFECT PARRY','gold');return}hp--;combo=1;P.inv=1;say(P.x,G-90,'HIT','red');if(hp<=0)end()}
function kill(o){o.hp--;if(o.hp>0)return;o.dead=1;let gain=o.type==='elite'?900:300;if(o.type==='air')s.stats.air++;if(o.type==='elite')s.stats.elite++;rg+=o.type==='elite'?4:1;score+=gain*combo*comboMult();combo=Math.min(30,combo+(o.type==='elite'?1.1:.7));peak=Math.max(peak,combo);rage=Math.min(100,rage+6*rageGain());if(o.type==='crystal')rg+=2;burst(o.x,o.y,20,'gold');say(o.x,o.y-20,'KO','cyan')}
function collide(o){if(o.dead||o.cool>0||o.lane!==P.l||Math.abs(o.x-P.x)>o.w*.55+34)return;o.cool=.2;if(o.type==='gem'||o.type==='crystal'){o.dead=1;rg+=o.type==='crystal'?3:1;score+=350*combo;combo=Math.min(30,combo+.35);peak=Math.max(peak,combo);s.stats.gems++;return}if(o.type==='air'){if(P.y>90||P.d){kill(o)}else hit();return}if(P.a||P.d)kill(o);else if(P.y>80){o.dead=1;score+=220*combo;combo=Math.min(30,combo+.5);peak=Math.max(peak,combo)}else hit()}
function startBoss(){if(boss)return;boss={x:W+180,hp:20,max:20,cool:.8};say(720,150,'WORLD GUARDIAN','gold')}
function bossUpdate(dt,sp){if(!boss)return;boss.x=Math.max(990,boss.x-sp*.25*dt);boss.cool-=dt;if(boss.cool<=0){boss.cool=.7+Math.random()*.5;const l=Math.floor(Math.random()*3);spawn('air',l,W+100);spawn('meteor',(l+1)%3,W+220)}if(Math.abs(boss.x-P.x)<120&&P.l===1){if(P.a||P.d){boss.hp--;score+=900*combo;combo=Math.min(30,combo+1);if(boss.hp<=0){boss=null;rg+=30;s.stats.boss++;say(1000,170,'GUARDIAN DEFEATED','gold')}}else hit()}}
function update(dt){t+=dt;const sp=Math.min(980,(430+t*7+combo*3)*worlds[world][2]);energy=Math.min(maxEnergy,energy+dt*11);P.a=Math.max(0,P.a-dt);P.d=Math.max(0,P.d-dt);P.par=Math.max(0,P.par-dt);P.inv=Math.max(0,P.inv-dt);P.x+=(L[P.l]-P.x)*Math.min(1,dt*15);P.v+=2200*dt;P.y+=P.v*dt;if(P.y<=0){P.y=0;P.v=0;P.j=0}spawn-=dt;if(spawn<=0){pattern();spawn=Math.max(.28,.86-t*.002)}if(rage>=100)rage=100;if(rage>=100&&t>20&&!boss&&Math.random()<.002)startBoss();for(let i=objs.length-1;i>=0;i--){const o=objs[i];o.x-=sp*dt;o.cool=Math.max(0,o.cool-dt);if(o.x<-200){objs.splice(i,1);continue}collide(o)}bossUpdate(dt,sp);if(combo>1)combo=Math.max(1,combo-dt*.065);score+=dt*sp*.035*combo*comboMult();if(t%5<dt)s.stats.time+=5/60;hud();if(Math.floor(t)!==Math.floor(t-dt))missionCheck()}
function burst(X,Y,n,type){for(let i=0;i<n;i++)parts.push({x:X,y:Y,vx:(Math.random()-.5)*500,vy:(Math.random()-.9)*420,l:.5+Math.random()*.5,type})}function say(X,Y,v,type){texts.push({x:X,y:Y,v,type,l:1})}
function scene(){const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,['#071b35','#321307','#dbeeff','#17103b','#03020c'][world]);g.addColorStop(1,['#08160f','#2b0906','#c9f5ff','#11153b','#05020d'][world]);x.fillStyle=g;x.fillRect(0,0,W,H);x.globalAlpha=.3;for(let i=0;i<70;i++){const sx=(i*137-t*20)%W;x.fillStyle='#fff';x.fillRect((sx+W)%W,40+(i*41)%260,2,2)}x.globalAlpha=1;x.fillStyle=['#09261b','#35120b','#b9d7e0','#17162f','#090712'][world];x.fillRect(0,G,W,H-G);for(const q of L){x.strokeStyle='rgba(150,230,255,.25)';x.beginPath();x.moveTo(q-60,G);x.lineTo(q-220,H);x.stroke();x.beginPath();x.moveTo(q+60,G);x.lineTo(q+220,H);x.stroke()}}
function dino(){const y=G-P.y;x.save();x.translate(P.x,y);if(P.inv&&Math.floor(P.inv*18)%2===0)x.globalAlpha=.35;const i=s.skin;x.shadowBlur=P.d?35:16;x.shadowColor=['#5cf0bd','#00eaff','#ff7b38','#9beaff','#ffe35a','#58ff9c','#d7c7ff','#a77bff','#fff08a','#8b7dff','#d7e9ff','#b58cff'][i];x.fillStyle=x.shadowColor;x.beginPath();x.ellipse(0,-45,34,46,0,0,7);x.fill();x.beginPath();x.ellipse(28,-82,35,29,-.1,0,7);x.fill();x.fillStyle='#08141b';x.beginPath();x.arc(43,-88,5,0,7);x.fill();x.fillStyle='rgba(255,255,255,.75)';x.fillRect(34,-70,25,4);x.fillStyle=x.shadowColor;x.fillRect(-25,-8,13,40);x.fillRect(12,-8,13,40);x.beginPath();x.moveTo(-25,-42);x.lineTo(-75,-62);x.lineTo(-30,-20);x.fill();if(i>=4){x.strokeStyle=x.shadowColor;x.lineWidth=5;x.beginPath();x.arc(0,-55,55,-2.4,1.2);x.stroke()}if(i>=8){x.fillStyle='rgba(255,255,255,.45)';x.beginPath();x.arc(0,-95,48,0,7);x.fill()}if(P.a){x.strokeStyle='#fff';x.lineWidth=9;x.beginPath();x.arc(48,-55,62,-1.2,1.1);x.stroke()}x.restore()}
function drawObjs(){for(const o of objs){if(o.dead)continue;x.save();x.translate(o.x,o.y);x.fillStyle=o.type==='meteor'?'#ff5a36':o.type==='crystal'?'#a77bff':o.type==='gem'?'#55eaff':o.type==='air'?'#c8f7ff':o.type==='elite'?'#ffcc55':'#6d8b80';x.shadowBlur=12;x.shadowColor=x.fillStyle;if(o.type==='spike'||o.type==='meteor'){x.beginPath();x.moveTo(-35,30);x.lineTo(0,-30);x.lineTo(35,30);x.closePath();x.fill()}else if(o.type==='gem'||o.type==='crystal'){x.rotate(Math.PI/4);x.fillRect(-15,-15,30,30)}else{x.beginPath();x.arc(0,0,o.w*.45,0,7);x.fill()}x.restore()}}
function hud(){if($('health'))$('health').textContent='●'.repeat(Math.max(0,hp))+'○'.repeat(Math.max(0,maxHp-hp));if($('energyText'))$('energyText').textContent=Math.floor(energy);if($('score'))$('score').textContent=Math.floor(score).toLocaleString();if($('combo'))$('combo').textContent='x'+combo.toFixed(1);if($('gems'))$('gems').textContent=(s.gems+Math.floor(rg*gemMult())).toLocaleString();if($('guardianHud'))$('guardianHud').textContent=boss?'BOSS':'RUN';if($('energyBar'))$('energyBar').style.width=energy/maxEnergy*100+'%';if($('rageBar'))$('rageBar').style.width=rage+'%';if($('bossBar'))$('bossBar').style.width=boss?boss.hp/boss.max*100+'%':'0%';if($('bestScore'))$('bestScore').textContent=s.best.toLocaleString();if($('rank'))$('rank').textContent=s.best>=60000?'MYTHIC':s.best>=30000?'LEGEND':s.best>=15000?'ELITE':s.best>=5000?'HUNTER':'ROOKIE'}
function draw(){scene();drawObjs();for(const q of parts){x.globalAlpha=Math.max(0,q.l);x.fillStyle=q.type==='red'?'#ff5555':q.type==='violet'?'#bd7cff':q.type==='gold'?'#ffd95a':'#6eeeff';x.fillRect(q.x,q.y,5,5)}x.globalAlpha=1;dino();for(const q of texts){x.globalAlpha=q.l;x.fillStyle='#fff';x.font='bold 22px Arial';x.textAlign='center';x.fillText(q.v,q.x,q.y)}x.globalAlpha=1}
function loop(now){if(!run)return;if(!pause){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw()}else last=now;requestAnimationFrame(loop)}
$('codeInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('redeemButton')?.click()});$('redeemButton')?.addEventListener('click',()=>{const input=$('codeInput'),msg=$('codeMessage');const code=(input?.value||'').trim().toUpperCase();const rewards={TRILLION1:1000000000000,DINO100:100,LEGEND500:500,FANTASY1K:1000,MYTHIC50K:50000,LEGENDARY1M:1000000};if(!code){msg.textContent='ENTER A CODE';return}if(s.used?.includes(code)){msg.textContent='ALREADY REDEEMED';return}if(rewards[code]){s.gems+=rewards[code];s.used=(s.used||[]).concat(code);save();msg.textContent='REWARD ADDED: '+rewards[code].toLocaleString()+' GEMS';renderMeta();hud()}else msg.textContent='INVALID CODE'});
renderMeta();hud();
})();