"use strict";
/* DINO LEGENDS V40 — Ascension gameplay engine */
const $=id=>document.getElementById(id),canvas=$("gameCanvas"),ctx=canvas.getContext("2d");
const SAVE="DINO_LEGENDS_V40";
const worlds=[
{id:"forest",name:"Enchanted Forest",icon:"🌲",color:"#35d88b",req:0,danger:1,boss:"Moss Titan"},{id:"moon",name:"Moonlit Ruins",icon:"🌙",color:"#8f7cff",req:2500,danger:1.25,boss:"Lunar Warden"},{id:"volcano",name:"Dragon Volcano",icon:"🔥",color:"#ff684d",req:10000,danger:1.55,boss:"Inferno Dragon"},{id:"ice",name:"Frozen Kingdom",icon:"❄️",color:"#62ecff",req:25000,danger:1.85,boss:"Frost Queen"},{id:"void",name:"Astral Void",icon:"🌌",color:"#c05cff",req:100000,danger:2.25,boss:"Void Emperor"}];
const skins=[["Arthur Rex","KNIGHT",0,"#d9b36c"],["Ghost Rex","PHANTOM",5000,"#aeb8c8"],["Cyber Rex","MYTHIC",25000,"#28d7ff"],["Samurai Rex","SHADOW",60000,"#ff62c7"],["Dragon Lord","ANCIENT",150000,"#ff8b45"],["Ice Emperor","FROSTBORN",400000,"#62ecff"],["Void Emperor","COSMIC",1000000,"#c084ff"],["Golden Titan","ROYAL",2500000,"#ffe89a"],["Galaxy Rex","GALACTIC",7000000,"#e2a7ff"],["Eternal Dragon","ETERNAL",20000000,"#fff"]];
while(skins.length<100){let i=skins.length,h=i*37%360;skins.push(["Legendary Beast "+(i+1),i<50?"LEGENDARY":i<80?"MYTHIC":"DIVINE",Math.floor(20000000*Math.pow(1.035,i-9)),`hsl(${h},85%,65%)`])}
const relics=[["Solar Core","☀️","+18% score","score",.18,6000],["Sky Feather","🪽","+22% jump height","jump",.22,9000],["Void Magnet","🧲","+35% gem pickup","magnet",.35,12000],["Dragon Heart","❤️‍🔥","+1 max health","health",1,18000],["Chrono Shard","⏳","+20% dash duration","dash",.2,25000],["Crown of Kings","👑","+30% rewards","reward",.3,50000]];
const missions=[["runner","🏃","Realm Runner","Launch 3 adventures",3,2500],["gems","💎","Crystal Hunter","Collect 500 gems",500,6000],["jumps","🪽","Sky Master","Jump 60 times",60,7000],["dash","⚡","Lightning","Dash 30 times",30,9000],["boss","👑","Guardian Slayer","Defeat a boss",1,15000],["score","🏆","Score Legend","Reach 50000 score",50000,25000]];
const achievements=[["first","FIRST LEGEND","Launch your first adventure",s=>s.runs>=1,1000],["ten","ROAD WARRIOR","Launch 10 adventures",s=>s.runs>=10,5000],["score","SCORE BREAKER","Reach 10000 best score",s=>s.best>=10000,10000],["boss","BOSS HUNTER","Defeat 3 bosses",s=>s.bosses>=3,20000],["collector","CREATURE COLLECTOR","Own 10 skins",s=>s.owned.length>=10,25000],["relic","RELIC FORGE","Equip 3 relics",s=>s.relics.length>=3,30000],["streak","SEVEN DAYS","Reach a 7 day streak",s=>s.streak>=7,50000],["million","MILLIONAIRE","Collect 1,000,000 lifetime gems",s=>s.totalGems>=1000000,100000],["void","VOID WALKER","Unlock Astral Void",s=>s.best>=100000,75000],["combo","COMBO KING","Reach x20 combo",s=>s.maxCombo>=20,40000],["speed","SPEED DEMON","Reach speed level 10",s=>s.upgrades.speed>=10,50000],["eternal","ETERNAL","Own Eternal Dragon",s=>s.owned.includes(99),250000]];
const base={gems:2500,best:0,skin:0,world:"forest",owned:[0],relics:[],used:[],runs:0,totalGems:0,jumps:0,dash:0,bosses:0,maxCombo:1,streak:1,lastDay:"",claimed:[],missions:{},upgrades:{speed:0,jump:0,shield:0,magnet:0},achievements:[],event:-1,migrated:false};
function copy(o){return JSON.parse(JSON.stringify(o))}function load(){try{return JSON.parse(localStorage.getItem(SAVE)||"null")||copy(base)}catch{return copy(base)}}let save={...copy(base),...load()};save.upgrades={...base.upgrades,...save.upgrades};save.missions={...base.missions,...save.missions};function persist(){localStorage.setItem(SAVE,JSON.stringify(save))}
try{let old=JSON.parse(localStorage.getItem("DINO_LEGENDS_V20")||"null");if(old&&!save.migrated){save.gems=Math.max(save.gems,old.gems||0);save.best=Math.max(save.best,old.best||0);save.owned=[...new Set([...(old.owned||[0]),...save.owned])];save.totalGems=Math.max(save.totalGems,old.totalGems||0);save.migrated=true;persist()}}catch{}
let score=0,health=3,combo=1,running=false,paused=false,last=0,spawn=0,distance=0,gemRun=0,boss=null,obstacles=[],gems=[],particles=[],timeScale=1;
const player={x:155,y:420,w:56,h:62,vy:0,jumps:0,ground:true,dash:0,shield:0,ability:0,inv:0};
const fmt=n=>Math.floor(Number(n)||0).toLocaleString(),level=()=>Math.max(1,Math.floor(save.best/2500)+1);function rank(){let l=level();return l>=60?"DIVINE":l>=40?"MYTHIC":l>=25?"LEGEND":l>=15?"ELITE":l>=5?"HUNTER":"ROOKIE"}function world(){return worlds.find(w=>w.id===save.world)||worlds[0]}function power(){return 100+save.upgrades.speed*8+save.upgrades.jump*7+save.upgrades.shield*9+save.upgrades.magnet*6+save.relics.length*18}
function ui(){$("gems").textContent=fmt(save.gems);$("bestScore").textContent=fmt(save.best);$("level").textContent=level();$("streak").textContent=save.streak;$("score").textContent=fmt(score);$("combo").textContent="x"+combo;$("health").textContent="❤️".repeat(Math.max(0,health))+"🖤".repeat(Math.max(0,3-health));$("currentWorldHud").textContent=world().name.replace(/Enchanted |Moonlit |Dragon |Frozen |Astral /,"").toUpperCase();$("profileName").textContent=skins[save.skin][0];$("profileLevel").textContent=level();$("rank").textContent=rank();$("profileBest").textContent=fmt(save.best);$("runs").textContent=fmt(save.runs);$("totalGems").textContent=fmt(save.totalGems);$("bossesDefeated").textContent=save.bosses;$("power").textContent=power();let xp=save.best%2500;$("xpBar").style.width=xp/25+"%";$("xpText").textContent=`${fmt(xp)} / 2500 XP`;$("skinCount").textContent=`${save.owned.length} / 100`;$("ccStreak").textContent=save.streak;renderAvatar();renderCommand()}
function renderAvatar(){let c=skins[save.skin]||skins[0];$("avatar").innerHTML=`<div class="heroDino" style="--cyan:${c[3]}">🦖</div>`;$("startAvatar").innerHTML=`<div class="heroDino" style="--cyan:${c[3]}">🦖</div>`}function toast(a,b){let t=document.createElement("div");t.className="toast";t.innerHTML=`<b>${a}</b><br><small>${b}</small>`;document.body.appendChild(t);requestAnimationFrame(()=>t.classList.add("show"));setTimeout(()=>{t.classList.remove("show");setTimeout(()=>t.remove(),300)},3000)}function banner(t){let e=$("runBanner");e.textContent=t;e.classList.remove("show");void e.offsetWidth;e.classList.add("show")}
function daily(){let d=[{id:"runner",name:"Adventure Starter",target:3},{id:"gems",name:"Crystal Hunter",target:500},{id:"jumps",name:"Skybound",target:40},{id:"dash",name:"Lightning Run",target:15}];return d[Math.floor(Date.now()/86400000)%d.length]}function abilityName(){return ["Roar","Time Rift","Meteor Call","Void Pulse"][Math.min(3,Math.floor((save.relics.length+save.upgrades.speed)/5))]}
function renderCommand(){let d=daily(),v=Math.min(d.target,Number(save.missions[d.id]||0));$("dailyTitle").textContent=d.name;$("dailyProgress").style.width=v/d.target*100+"%";$("dailyText").textContent=`${fmt(v)} / ${fmt(d.target)}`;$("achievementCount").textContent=`${save.achievements.length}/${achievements.length}`;$("abilityName").textContent=abilityName();$("abilityReady").textContent=player.ability<=0?"READY":"COOLDOWN"}
function card(icon,title,desc,price,a,disabled=false){return `<article class="item" style="--glow:${a.color||"#62ecff"}"><div class="icon">${icon}</div><h3>${title}</h3><small>${desc}</small><p>${a.text||""}</p><footer><span class="price">${price}</span><button class="action" ${disabled?"disabled":""} data-act="${a.id}" data-val="${a.val??""}">${a.label||"SELECT"}</button></footer></article>`}
function renderSkins(){let g=$("skinGrid");g.innerHTML=skins.map((s,i)=>card("🦖",s[0],s[1],i===save.skin?"EQUIPPED":fmt(s[2])+" 💎",{id:"skin",val:i,label:save.skin===i?"EQUIPPED":save.owned.includes(i)?"EQUIP":"BUY",text:"Cosmetic creature with a unique neon aura.",color:s[3]},!save.owned.includes(i)&&save.gems<s[2]&&i!==save.skin)).join("");g.querySelectorAll("button").forEach(b=>b.onclick=()=>skin(+b.dataset.val))}function skin(i){let s=skins[i];if(!save.owned.includes(i)){if(save.gems<s[2])return toast("NOT ENOUGH GEMS",`Need ${fmt(s[2])}`);save.gems-=s[2];save.owned.push(i);toast("SKIN UNLOCKED",s[0])}save.skin=i;persist();renderSkins();ui();checkAchievements()}
function renderWorlds(){let g=$("worldGrid");g.innerHTML=worlds.map(w=>card(w.icon,w.name,`DANGER ×${w.danger}`,w.id===save.world?"ACTIVE":`BEST ${fmt(w.req)}+`,{id:"world",val:w.id,label:w.id===save.world?"ACTIVE":"ENTER",text:`Guardian: ${w.boss}`,color:w.color},save.best<w.req)).join("");g.querySelectorAll("button").forEach(b=>b.onclick=()=>{save.world=b.dataset.val;persist();renderWorlds();ui();banner(world().name.toUpperCase())})}
function renderRelics(){let g=$("relicGrid");g.innerHTML=relics.map((r,i)=>{let own=save.relics.includes(i);return card(r[1],r[0],r[2],own?"EQUIPPED":fmt(r[5])+" 💎",{id:"relic",val:i,label:own?"EQUIPPED":"FORGE",text:"Equip up to 3 relics; effects stack.",color:"#62ecff"},!own&&save.gems<r[5]||!own&&save.relics.length>=3)}).join("");g.querySelectorAll("button").forEach(b=>b.onclick=()=>relic(+b.dataset.val))}function relic(i){if(save.relics.includes(i))return;if(save.relics.length>=3)return toast("RELIC SLOTS FULL","Three active relics maximum.");let r=relics[i];if(save.gems<r[5])return toast("FORGE BLOCKED","Not enough gems");save.gems-=r[5];save.relics.push(i);persist();renderRelics();ui();toast("RELIC EQUIPPED",r[0]);checkAchievements()}
function renderShop(){let defs=["speed","jump","shield","magnet"],names=["Turbo Core","Sky Engine","Guardian Plating","Gem Radar"],icons=["🏎️","🪽","🛡️","🧲"];let g=$("shopGrid");g.innerHTML=defs.map((k,i)=>{let lv=save.upgrades[k],cost=Math.floor(3000*Math.pow(1.65,lv));return card(icons[i],names[i],`LEVEL ${lv}/25`,fmt(cost)+" 💎",{id:"upgrade",val:k,label:lv>=25?"MAX":"UPGRADE",text:["Faster scroll and score","Higher jumps","Better survivability","Larger gem pickup"][i],color:"#8067ff"},lv>=25||save.gems<cost)}).join("");g.querySelectorAll("button").forEach(b=>b.onclick=()=>upgrade(b.dataset.val))}function upgrade(k){let lv=save.upgrades[k],cost=Math.floor(3000*Math.pow(1.65,lv));if(lv>=25||save.gems<cost)return;save.gems-=cost;save.upgrades[k]++;persist();renderShop();ui();toast("UPGRADE COMPLETE",`${k.toUpperCase()} Lv.${save.upgrades[k]}`);checkAchievements()}
function renderMissions(){let g=$("missionGrid");g.innerHTML=missions.map(m=>{let v=Number(save.missions[m[0]]||0),done=v>=m[4],claimed=save.claimed.includes(m[0]);return card(m[1],m[2],m[3],claimed?"CLAIMED":fmt(m[5])+" 💎",{id:"mission",val:m[0],label:claimed?"CLAIMED":done?"CLAIM":"PROGRESS",text:`${fmt(Math.min(v,m[4]))} / ${fmt(m[4])}`,color:"#ffd866"},claimed||!done)}).join("");g.querySelectorAll("button").forEach(b=>b.onclick=()=>claimMission(b.dataset.val))}function claimMission(id){if(save.claimed.includes(id))return;let m=missions.find(x=>x[0]===id);if(!m||Number(save.missions[id]||0)<m[4])return;save.claimed.push(id);save.gems+=m[5];save.totalGems+=m[5];persist();renderMissions();ui();toast("QUEST COMPLETE",`+${fmt(m[5])} gems`)}
function checkAchievements(){for(let a of achievements)if(!save.achievements.includes(a[0])&&a[3](save)){save.achievements.push(a[0]);save.gems+=a[4];save.totalGems+=a[4];toast("🏆 ACHIEVEMENT",`${a[1]} • +${fmt(a[4])} gems`)}persist();ui()}
function openAchievements(){let c=$("modalContent");c.innerHTML=`<div class="eyebrow">PERMANENT PROGRESSION</div><h2>ACHIEVEMENTS</h2><div class="modalGrid">${achievements.map(a=>{let ok=save.achievements.includes(a[0])||a[3](save);return `<article class="modalCard"><b>${ok?"🏆":"🔒"} ${a[1]}</b><small>${a[2]}<br><br>Reward: 💎 ${fmt(a[4])}</small></article>`}).join("")}</div>`;$("modal").classList.remove("hidden")}
function eventData(){return[{name:"Meteor Rush",desc:"Collect gems during the cosmic shower.",target:5000,reward:30000,icon:"☄️"},{name:"Guardian Hunt",desc:"Defeat realm guardians.",target:1,reward:50000,icon:"👑"},{name:"Combo Festival",desc:"Build a legendary combo.",target:20,reward:40000,icon:"🔥"}][Math.floor(Date.now()/604800000)%3]}function renderEvent(){let e=eventData(),v=e.name==="Meteor Rush"?gemRun:e.name==="Guardian Hunt"?save.bosses:save.maxCombo;$("eventName").textContent=e.name;$("eventDesc").textContent=e.desc;$("eventProgress").style.width=Math.min(100,v/e.target*100)+"%";$("eventText").textContent=`${fmt(v)} / ${fmt(e.target)}`;$("eventClaim").disabled=v<e.target||save.event===Math.floor(Date.now()/604800000);$("eventClaim").onclick=()=>{if($("eventClaim").disabled)return;save.gems+=e.reward;save.totalGems+=e.reward;save.event=Math.floor(Date.now()/604800000);persist();ui();renderEvent();toast("EVENT COMPLETE",`+${fmt(e.reward)} gems`)}}
function reset(){score=0;health=3;combo=1;distance=0;spawn=0;gemRun=0;obstacles=[];gems=[];particles=[];boss=null;Object.assign(player,{y:420,vy:0,jumps:0,ground:true,dash:0,shield:0,ability:0,inv:0})}
function start(){reset();running=true;paused=false;save.runs++;save.missions.runner=(save.missions.runner||0)+1;$("startScreen").classList.add("hidden");$("gameOverScreen").classList.add("hidden");$("pauseScreen").classList.add("hidden");last=performance.now();toast("ADVENTURE STARTED",world().name);requestAnimationFrame(loop)}function finish(win=false){running=false;save.best=Math.max(save.best,Math.floor(score));if(win){save.bosses++;save.missions.boss=(save.missions.boss||0)+1}persist();$("finalScore").textContent=fmt(score);$("resultEyebrow").textContent=win?"GUARDIAN DEFEATED":"RUN COMPLETE";$("resultTitle").innerHTML=win?"REALM <b>CONQUERED</b>":"LEGEND <b>FINISHED</b>";$("resultStats").innerHTML=`<span>💎 ${fmt(gemRun)} GEMS</span><span>🔥 x${combo}</span><span>📏 ${fmt(distance)}m</span>`;$("gameOverScreen").classList.remove("hidden");ui();checkAchievements()}
function jump(){if(!running||paused)return;if(player.ground||player.jumps<2){player.vy=-(12.5+save.upgrades.jump*.28);player.ground=false;player.jumps++;save.jumps++;save.missions.jumps=(save.missions.jumps||0)+1;sound(520,.05)}}function dash(){if(!running||paused||player.dash>0)return;player.dash=380;save.dash++;save.missions.dash=(save.missions.dash||0)+1;particles.push(...burst(player.x,player.y,16,world().color));sound(160,.08)}function shield(){if(!running||paused)return;player.shield=160;sound(220,.06)}function ability(){if(!running||paused||player.ability>0)return;player.ability=900;let a=abilityName();banner(a.toUpperCase());if(a==="Roar"){obstacles=[];combo+=3}else if(a==="Time Rift"){timeScale=.45;setTimeout(()=>timeScale=1,1800)}else if(a==="Meteor Call"){for(let i=0;i<8;i++)obstacles.push({x:canvas.width+i*150,y:300+Math.random()*100,w:30,h:30,kind:"meteor",vx:12})}else{obstacles=[];score+=5000}sound(780,.15)}
function spawnStuff(){let w=world(),speed=6+w.danger+save.upgrades.speed*.15;spawn-=speed;if(spawn<=0){spawn=70+Math.random()*100;let h=35+Math.random()*55;obstacles.push({x:canvas.width+30,y:482-h,w:28+Math.random()*30,h,kind:Math.random()<.15?"crystal":"rock",vx:speed})}if(Math.random()<.025+save.upgrades.magnet*.001)gems.push({x:canvas.width+20,y:330+Math.random()*100,r:10})}
function bossCheck(){if(boss||score<world().req+10000)return;boss={hp:100,x:980,t:0};$("bossName").textContent=world().boss;$("bossHud").classList.remove("hidden");banner("⚠ GUARDIAN APPROACHING")}
function hit(){if(player.inv>0||player.shield>0||player.dash>0)return;health--;combo=1;player.inv=900;document.body.classList.add("shake");setTimeout(()=>document.body.classList.remove("shake"),350);if(health<=0)finish(false)}function collect(){for(let i=gems.length-1;i>=0;i--){let g=gems[i];if(Math.hypot(player.x+25-g.x,player.y+25-g.y)<50+save.upgrades.magnet*7){gems.splice(i,1);let v=1+Math.floor(save.upgrades.magnet/3);save.gems+=v;save.totalGems+=v;gemRun+=v;save.missions.gems=(save.missions.gems||0)+v;score+=25;combo=Math.min(30,combo+1);save.maxCombo=Math.max(save.maxCombo,combo);particles.push(...burst(g.x,g.y,8,"#62ecff"))}}}
function collide(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function update(dt){let w=world(),speed=(6+w.danger+save.upgrades.speed*.15)*timeScale;distance+=speed*dt/16;score+=speed*dt*.7*combo;spawnStuff();bossCheck();player.vy+=.65*dt/16;player.y+=player.vy*dt/16;if(player.y>=420){player.y=420;player.vy=0;player.ground=true;player.jumps=0}if(player.dash>0)player.dash-=dt;if(player.shield>0)player.shield-=dt;if(player.ability>0)player.ability-=dt;if(player.inv>0)player.inv-=dt;for(let i=obstacles.length-1;i>=0;i--){let o=obstacles[i];o.x-=o.vx*dt/16;if(collide({x:player.x+9,y:player.y+8,w:38,h:48},o)){if(o.kind==="crystal"){score+=200;combo++;obstacles.splice(i,1);continue}hit();obstacles.splice(i,1)}else if(o.x<-80)obstacles.splice(i,1)}for(let g of gems)g.x-=speed*dt/16;collect();for(let p of particles){p.x+=p.vx*dt/16;p.y+=p.vy*dt/16;p.life-=dt;p.vy+=.08}particles=particles.filter(p=>p.life>0);if(boss){boss.t+=dt;boss.x=900+Math.sin(boss.t/500)*100;if(Math.random()<.012)obstacles.push({x:boss.x-20,y:300+Math.random()*100,w:34,h:34,kind:"meteor",vx:7+w.danger});if(player.dash>0&&Math.abs(player.x-boss.x)<180){boss.hp-=.8*dt/16;score+=120*dt/16}if(boss.hp<=0){boss=null;$("bossHud").classList.add("hidden");finish(true);return}$("bossHp").style.width=boss.hp+"%";$("bossHpText").textContent=Math.ceil(boss.hp)+"%"}}
function draw(){let w=world(),W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,w.color+"44");g.addColorStop(1,"#050611");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="#fff2";for(let i=0;i<10;i++){let x=(i*180-distance*.7%180);ctx.beginPath();ctx.arc(x,100+(i%3)*45,2+i%4,0,7);ctx.fill()}ctx.fillStyle="#10152a";ctx.fillRect(0,482,W,78);ctx.strokeStyle=w.color+"66";ctx.beginPath();ctx.moveTo(0,482);ctx.lineTo(W,482);ctx.stroke();for(let x=-(distance*2%80);x<W;x+=80){ctx.fillStyle=w.color+"22";ctx.fillRect(x,495,35,4)}for(let q of gems){ctx.fillStyle="#62ecff";ctx.shadowBlur=18;ctx.shadowColor="#62ecff";ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,7);ctx.fill();ctx.shadowBlur=0}for(let o of obstacles){ctx.fillStyle=o.kind==="meteor"?"#ff557f":o.kind==="crystal"?"#62ecff":"#6d604e";ctx.beginPath();ctx.roundRect(o.x,o.y,o.w,o.h,8);ctx.fill()}ctx.font="62px Arial";ctx.textAlign="center";if(!(player.inv>0&&Math.floor(player.inv/80)%2===0))ctx.fillText("🦖",player.x+28,player.y+55);if(player.shield>0){ctx.strokeStyle="#62ecff";ctx.lineWidth=4;ctx.beginPath();ctx.arc(player.x+28,player.y+30,48,0,7);ctx.stroke()}if(boss){ctx.font="70px Arial";ctx.fillText("👑",boss.x,300);ctx.font="12px Orbitron";ctx.fillStyle="#fff";ctx.fillText(world().boss,boss.x,340)}for(let p of particles){ctx.globalAlpha=Math.max(0,p.life/500);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4)}ctx.globalAlpha=1}
function burst(x,y,n,c){return Array.from({length:n},()=>({x,y,vx:(Math.random()-.5)*8,vy:(Math.random()-.5)*8,life:300+Math.random()*300,color:c}))}function loop(t){if(!running)return;if(paused){last=t;requestAnimationFrame(loop);return}let dt=Math.min(32,t-last||16);last=t;update(dt);draw();ui();requestAnimationFrame(loop)}
function sound(f,d){try{let A=window.AudioContext||window.webkitAudioContext;if(!sound.ctx)sound.ctx=new A();let o=sound.ctx.createOscillator(),g=sound.ctx.createGain();o.frequency.value=f;g.gain.value=.025;o.connect(g);g.connect(sound.ctx.destination);o.start();o.stop(sound.ctx.currentTime+d)}catch{}}
function redeem(){let i=$("codeInput"),c=i.value.trim().toUpperCase(),codes={DINO100:100,LEGEND500:500,FANTASY1K:1000,MYTHIC50K:50000,LEGENDARY1M:1000000,ASCENSION40:40000000};if(!c)return msg("ENTER A REWARD CODE");if(save.used.includes(c))return msg("❌ CODE ALREADY USED");if(codes[c]==null)return msg("❌ INVALID CODE");let r=codes[c];save.gems+=r;save.totalGems+=r;save.used.push(c);persist();i.value="";msg(`🎉 REDEEMED +${fmt(r)} GEMS`,true);ui()}function msg(t,ok=false){let e=$("codeMessage");e.textContent=t;e.style.color=ok?"#67ffad":"#ff7b9b"}
function bind(){$("startButton").onclick=start;$("restartButton").onclick=start;$("resumeButton").onclick=()=>{paused=false;$("pauseScreen").classList.add("hidden")};$("jumpButton").onclick=jump;$("dashButton").onclick=dash;$("shieldButton").onclick=shield;$("abilityButton").onclick=ability;$("achievementsButton").onclick=openAchievements;$("closeModal").onclick=()=>$("modal").classList.add("hidden");$("redeemButton").onclick=redeem;$("codeInput").onkeydown=e=>{if(e.key==="Enter")redeem()};window.onkeydown=e=>{if(e.code==="Space"||e.code==="ArrowUp"){e.preventDefault();jump()}else if(e.code==="KeyD")dash();else if(e.code==="KeyS")shield();else if(e.code==="KeyQ")ability();else if(e.code==="Escape"&&running){paused=!paused;$("pauseScreen").classList.toggle("hidden",!paused)}}}
function tabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.panel).classList.add("active")})}function stars(){let s=$("stars");for(let i=0;i<55;i++){let e=document.createElement("i");e.className="star";e.style.left=Math.random()*100+"%";e.style.top=Math.random()*100+"%";e.style.animationDuration=8+Math.random()*18+"s";e.style.animationDelay=-Math.random()*15+"s";s.appendChild(e)}}
function init(){stars();tabs();bind();renderSkins();renderWorlds();renderRelics();renderShop();renderMissions();renderEvent();ui();setInterval(()=>{renderEvent();checkAchievements()},2500)}init();
