(()=>{
'use strict';
const $=id=>document.getElementById(id),canvas=$('gameCanvas');if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;
const W=1440,H=760,G=590,LANES=[350,720,1090],SAVE='DINO_LEGENDS_V24';
const SKINS=[
 ['Verdant Rex','🌿','#55e58c','NATURE','RARE'],['Ember Fang','🔥','#ff7043','FIRE','RARE'],['Frost Claw','❄️','#67e8ff','ICE','RARE'],['Volt Raptor','⚡','#ffe05c','STORM','EPIC'],['Void Stalker','🌑','#b477ff','VOID','EPIC'],['Solar Tyrant','☀️','#ffd45c','SOLAR','EPIC'],['Crystal Drake','💎','#ff7de3','CRYSTAL','EPIC'],['Toxic Hunter','☣️','#a8ff57','TOXIC','LEGENDARY'],['Cyber Rex','🤖','#35dcff','CYBER','LEGENDARY'],['Shadow Warden','🗡️','#d18cff','SHADOW','LEGENDARY'],['Ocean Leviathan','🌊','#55aaff','OCEAN','LEGENDARY'],['Lava Colossus','🌋','#ff594d','MAGMA','LEGENDARY'],['Thunder King','🌩️','#aebdff','THUNDER','MYTHIC'],['Moon Beast','🌙','#c8b7ff','MOON','MYTHIC'],['Star Eater','✨','#ffe58a','COSMIC','MYTHIC'],['Bloodmoon Rex','🩸','#ff6c86','BLOOD','MYTHIC'],['Ancient Guardian','🗿','#d0a77a','ANCIENT','DIVINE'],['Neon Phantom','💠','#5fffe2','NEON','DIVINE'],['Chrono Dragon','⏳','#9bb6ff','CHRONO','DIVINE'],['Galaxy Emperor','🌌','#c98cff','GALAXY','DIVINE'],['Omega Titan','⚔️','#ffffff','OMEGA','DIVINE'],['Prism Overlord','🔷','#ff9eea','PRISM','DIVINE'],['Inferno Prime','🔥','#ffb347','PRIME','DIVINE'],['Dino Legend','👑','#ffe77a','LEGEND','DIVINE']
];
const WORLDS=[['Emerald Jungle','🌿',0,1],['Ashen Volcano','🌋',9000,1.1],['Frozen Expanse','❄️',22000,.96],['Sky Citadel','🏛️',42000,1.06],['Neon Abyss','💠',70000,1.15],['Cosmic Rift','🌌',110000,1.24]];
const UP=[['Vital Core','❤️','+1 maximum HP',700],['Energy Reactor','⚡','+20 maximum energy',1000],['Dash Drive','💨','-5 dash energy cost',1300],['Combo Engine','🔥','+10% combo score',1800],['Gem Magnet','🧲','+25% run gems',2200],['Parry Matrix','🛡️','+0.10s parry window',2700],['Rage Reactor','☄️','+20% rage gain',3200],['Lucky Core','🍀','better rare-event odds',3900],['Hunter Protocol','🎯','+8% enemy score',4600],['Guardian Core','👑','+12% boss damage',5500]];
const MISS=[['Combo Architect','Reach x12 combo',12],['Gem Rush','Collect 40 run gems',40],['Air Hunter','Defeat 20 airborne enemies',20],['Elite Breaker','Defeat 25 elites',25],['Perfect Guard','Land 12 perfect parries',12],['Guardian Hunter','Defeat 4 guardians',4],['Long Haul','Survive 150 seconds',150],['Explorer','Unlock 4 worlds',4]];
const D={gems:2500,best:0,skin:0,owned:[0],up:{},world:0,missions:{},stats:{gems:0,air:0,elite:0,parry:0,boss:0,time:0}};
const clone=o=>JSON.parse(JSON.stringify(o));function load(){try{const v=JSON.parse(localStorage.getItem(SAVE));return {...clone(D),...v,owned:Array.isArray(v.owned)?[...new Set(v.owned)]:[0],up:v.up||{},missions:v.missions||{},stats:{...D.stats,...(v.stats||{})}}}catch{return clone(D)}}
let save=load();const persist=()=>localStorage.setItem(SAVE,JSON.stringify(save));
let running=false,paused=false,last=0,time=0,score=0,runGems=0,hp=3,maxHp=3,energy=100,maxEnergy=100,rage=0,combo=1,peak=1,world=save.world||0,spawn=.5,boss=null,objects=[],particles=[],texts=[],shake=0,stars=[],dust=[];
const P={lane:1,x:720,y:0,vy:0,jumps:0,attack:0,dash:0,parry:0,inv:0};
const up=i=>Number(save.up[i]||0),gemMult=()=>1+up(4)*.25,scoreMult=()=>1+up(3)*.1+up(8)*.08,dashCost=()=>Math.max(12,34-up(2)*5),parryWindow=()=>.28+up(5)*.1,rageMult=()=>1+up(6)*.2;
const pal=[['#071c20','#123c2b','#0a4d39'],['#210a08','#5a1b0c','#a42c0b'],['#0a1830','#204b78','#b7e7ff'],['#11122e','#2b2460','#6f75c9'],['#020d18','#062b38','#00b8a9'],['#0a051c','#25104c','#7d3cff']];
for(let i=0;i<90;i++)stars.push({x:Math.random()*W,y:Math.random()*360,r:.5+Math.random()*2,a:.2+Math.random()*.8,s:.2+Math.random()*.8});
for(let i=0;i<40;i++)dust.push({x:Math.random()*W,y:G-30-Math.random()*150,r:1+Math.random()*3,s:.4+Math.random()*1.4});
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)}addEventListener('resize',resize,{passive:true});resize();
function panel(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id))}document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>panel(b.dataset.panel));
function esc(s){return String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function render(){
 const s=$('skins');if(s)s.innerHTML=`<div class="heading"><div><small>LEGEND VAULT · ${save.owned.length}/${SKINS.length} COLLECTED</small><h2>SKIN FORGE</h2></div><b>${save.gems.toLocaleString()} GEMS</b></div><div class="grid skinGrid">${SKINS.map((v,i)=>{const owned=save.owned.includes(i),active=save.skin===i,price=i?Math.floor(1200*Math.pow(1.34,i)):0;return `<article class="item skinCard ${active?'selected':''}" style="--glow:${v[2]}"><div class="skinPreview"><div class="aura"></div><div class="dinoGlyph">🦖</div><b>${v[1]}</b></div><div class="skinTags"><span>${v[4]}</span><span>${v[3]}</span></div><h3>${esc(v[0])}</h3><small>UNIQUE SILHOUETTE · AURA · TRAIL</small><div class="skinStats"><i>⚡ ${100+i%8*3}</i><i>🛡 ${100+i%6*4}</i><i>✦ ${100+i%7*5}</i></div><footer><span class="price">${owned?(active?'EQUIPPED':'OWNED'):price.toLocaleString()+' GEMS'}</span><button class="action skinBtn" data-i="${i}" ${!owned&&save.gems<price?'disabled':''}>${owned?(active?'EQUIPPED':'EQUIP'):'UNLOCK'}</button></footer></article>`}).join('')}</div>`;
 const a=$('abilities');if(a)a.innerHTML=`<div class="heading"><div><small>10 SYSTEMS · 5 LEVELS EACH</small><h2>UPGRADE LAB</h2></div><b>${Object.values(save.up).reduce((x,y)=>x+Number(y||0),0)} LEVELS</b></div><div class="grid">${UP.map((u,i)=>{let lv=Math.min(5,up(i)),cost=Math.floor(u[3]*Math.pow(1.58,lv));return `<article class="item upgradeCard"><div class="icon">${u[1]}</div><h3>${u[0]}</h3><small>LEVEL ${lv}/5</small><p>${u[2]}</p><div class="levelDots">${[0,1,2,3,4].map(n=>`<i class="${n<lv?'on':''}"></i>`).join('')}</div><footer><span class="price">${lv>=5?'MAX':cost.toLocaleString()+' GEMS'}</span><button class="action upBtn" data-i="${i}" ${lv>=5||save.gems<cost?'disabled':''}>${lv>=5?'MAX':'UPGRADE'}</button></footer></article>`}).join('')}</div>`;
 const m=$('missions');if(m)m.innerHTML=`<div class="heading"><div><small>REWARD TRACK</small><h2>MISSIONS</h2></div></div>${MISS.map((q,i)=>{const v=missionValue(i),done=!!save.missions[i],reward=(i+1)*900;return `<div class="mission"><span><b>${q[0]}</b><small>${q[1]} · ${Math.min(q[2],v)}/${q[2]}</small></span><button class="action missBtn" data-i="${i}" ${done||v<q[2]?'disabled':''}>${done?'CLAIMED':'CLAIM '+reward}</button></div>`}).join('')}`;
 const w=$('worlds');if(w)w.innerHTML=`<div class="heading"><div><small>EXPEDITION NETWORK · ${world+1}/${WORLDS.length}</small><h2>WORLDS</h2></div></div><div class="grid">${WORLDS.map((q,i)=>`<article class="item worldCard ${save.world<i?'locked':''}" style="--glow:${['#55e58c','#ff7043','#67e8ff','#aebdff','#5fffe2','#c98cff'][i]}"><div class="worldIcon">${q[1]}</div><h3>${q[0]}</h3><small>${save.world>=i?'UNLOCKED':'BEST SCORE '+q[2].toLocaleString()}</small><p>Speed ×${q[3].toFixed(2)} · evolving hazards · unique atmosphere.</p><footer><button class="action worldBtn" data-i="${i}" ${save.world<i?'disabled':''}>${world===i?'ACTIVE':'ENTER'}</button></footer></article>`).join('')}</div>`;
 document.querySelectorAll('.skinBtn').forEach(b=>b.onclick=()=>buySkin(+b.dataset.i));document.querySelectorAll('.upBtn').forEach(b=>b.onclick=()=>buyUp(+b.dataset.i));document.querySelectorAll('.worldBtn').forEach(b=>b.onclick=()=>{world=+b.dataset.i;render();hud()});document.querySelectorAll('.missBtn').forEach(b=>b.onclick=()=>claim(+b.dataset.i));
}
function buySkin(i){const price=i?Math.floor(1200*Math.pow(1.34,i)):0;if(save.owned.includes(i))save.skin=i;else if(save.gems>=price){save.gems-=price;save.owned.push(i);save.skin=i}else return;persist();render();hud()}
function buyUp(i){const lv=up(i);if(lv>=5)return;const cost=Math.floor(UP[i][3]*Math.pow(1.58,lv));if(save.gems<cost)return;save.gems-=cost;save.up[i]=lv+1;persist();render();hud()}
function missionValue(i){const st=save.stats;return [peak,st.gems,st.air,st.elite,st.parry,st.boss,Math.floor(st.time),save.world+1][i]}
function claim(i){if(save.missions[i]||missionValue(i)<MISS[i][2])return;save.missions[i]=1;save.gems+=(i+1)*900;persist();render();hud()}
function start(){running=true;paused=false;time=0;score=0;runGems=0;maxHp=3+up(0);hp=maxHp;maxEnergy=100+up(1)*20;energy=maxEnergy;rage=0;combo=1;peak=1;spawn=.45;boss=null;objects=[];particles=[];texts=[];shake=0;Object.assign(P,{lane:1,x:720,y:0,vy:0,jumps:0,attack:0,dash:0,parry:0,inv:0});save.stats.runs=(save.stats.runs||0)+1;persist();$('startScreen')?.classList.add('hidden');$('gameOverScreen')?.classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function finish(){if(!running)return;running=false;const final=Math.floor(score),reward=Math.floor(runGems*gemMult());save.best=Math.max(save.best,final);save.gems+=reward;save.stats.gems+=runGems;save.stats.time+=time;while(save.world<WORLDS.length-1&&save.best>=WORLDS[save.world+1][2])save.world++;persist();render();$('finalScore').textContent=final.toLocaleString();$('finalStats').textContent=`${WORLDS[world][0]} · PEAK x${peak.toFixed(1)} · +${reward.toLocaleString()} GEMS`;$('gameOverScreen')?.classList.remove('hidden');hud()}
function act(a){if(!running||paused)return;if(a==='left')P.lane=Math.max(0,P.lane-1);if(a==='right')P.lane=Math.min(2,P.lane+1);if(a==='jump'&&P.jumps<2){P.vy=P.jumps?-790:-960;P.jumps++;burst(P.x,G-P.y,10,'cyan')}if(a==='attack')P.attack=.24;if(a==='dash'&&energy>=dashCost()){energy-=dashCost();P.dash=.34;P.inv=.48;burst(P.x,G-P.y,22,'gold')}if(a==='parry'&&energy>=20){energy-=20;P.parry=parryWindow()}if(a==='rage'&&rage>=100){rage=0;score+=2400*combo;combo=Math.min(35,combo+3);burst(P.x,G-P.y,34,'violet')}}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();act(b.dataset.action)}));addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft'||e.code==='KeyA')act('left');else if(e.code==='ArrowRight'||e.code==='KeyD')act('right');else if(e.code==='Space'||e.code==='ArrowUp')act('jump');else if(e.code==='KeyF')act('attack');else if(e.code==='ShiftLeft'||e.code==='ShiftRight')act('dash');else if(e.code==='KeyS')act('parry');else if(e.code==='KeyR')act('rage');else if(e.code==='Escape'&&running){paused=!paused;$('pauseScreen')?.classList.toggle('hidden',!paused);last=performance.now()}else if(e.code==='Enter'&&!running)start()});$('startButton')?.addEventListener('click',start);$('restartButton')?.addEventListener('click',start);$('resumeButton')?.addEventListener('click',()=>{paused=false;$('pauseScreen')?.classList.add('hidden');last=performance.now()});
function spawnObj(type,lane,x=W+80){const spec={rock:[72,65,G-30],spike:[72,45,G-12],enemy:[78,86,G-48],elite:[94,100,G-55],air:[82,52,390],gem:[34,34,G-125],meteor:[98,58,320],crystal:[44,60,G-165],drone:[76,52,300]}[type];if(spec)objects.push({type,lane,x,w:spec[0],h:spec[1],y:spec[2],hp:type==='elite'?2:1,cool:0,dead:false,rot:0,phase:Math.random()*7})}
function pattern(){const r=Math.random(),l=Math.floor(Math.random()*3),rare=.08+up(7)*.035;if(time<5){spawnObj(r<.7?'rock':'gem',l);return}if(r<rare){spawnObj('meteor',l);spawnObj('crystal',(l+1)%3,W+230)}else if(r<.25){spawnObj('enemy',l);spawnObj('air',(l+1)%3,W+220)}else if(r<.43){spawnObj('spike',l);spawnObj('rock',(l+1)%3,W+190)}else if(r<.58)spawnObj('elite',l);else if(r<.72){spawnObj('air',l);spawnObj('gem',(l+2)%3,W+190)}else{spawnObj('drone',l);spawnObj('spike',(l+2)%3,W+250)}}
function hit(){if(P.inv>0)return;if(P.parry>0){score+=700*combo;combo=Math.min(35,combo+1.8);peak=Math.max(peak,combo);rage=Math.min(100,rage+10*rageMult());P.parry=0;save.stats.parry++;pop(P.x,G-120,'PERFECT PARRY','gold');burst(P.x,G-90,24,'gold');return}hp--;combo=1;P.inv=1;shake=10;pop(P.x,G-100,'HIT','red');burst(P.x,G-80,16,'red');if(hp<=0)finish()}
function defeat(o){o.hp--;if(o.hp>0){pop(o.x,o.y-30,'BREAK','gold');return}o.dead=true;const elite=o.type==='elite';if(o.type==='air')save.stats.air++;if(elite)save.stats.elite++;runGems+=elite?5:(o.type==='crystal'?3:1);score+=(elite?1100:340)*combo*scoreMult();combo=Math.min(35,combo+(elite?1.2:.72));peak=Math.max(peak,combo);rage=Math.min(100,rage+7*rageMult());burst(o.x,o.y,elite?30:18,'gold');pop(o.x,o.y-25,elite?'ELITE DOWN':'KO','cyan')}
function collide(o){if(o.dead||o.cool>0||o.lane!==P.lane||Math.abs(o.x-P.x)>o.w*.55+32)return;o.cool=.16;if(o.type==='gem'||o.type==='crystal'){o.dead=true;runGems+=o.type==='crystal'?3:1;score+=400*combo;combo=Math.min(35,combo+.35);peak=Math.max(peak,combo);burst(o.x,o.y,12,'cyan');pop(o.x,o.y-25,'+ GEM','cyan');return}if(o.type==='air'||o.type==='drone'){if(P.y>70||P.dash>0||P.attack>0)defeat(o);else hit();return}if(P.attack>0||P.dash>0)defeat(o);else if(P.y>90){o.dead=true;score+=250*combo;combo=Math.min(35,combo+.5);peak=Math.max(peak,combo);burst(o.x,o.y,10,'gold')}else hit()}
function bossStart(){if(boss)return;boss={x:1190,hp:24,max:24,cool:.7,phase:0};pop(720,160,'GUARDIAN INCOMING','gold');burst(720,300,45,'violet')}
function bossUpdate(dt,speed){if(!boss)return;boss.x=Math.max(920,boss.x-speed*.18*dt);boss.phase+=dt;boss.cool-=dt;if(boss.cool<=0){boss.cool=.65+Math.random()*.6;const l=Math.floor(Math.random()*3);spawnObj('meteor',l,W+120);spawnObj('air',(l+1)%3,W+260)}if(Math.abs(boss.x-P.x)<150&&P.lane===1){if(P.attack>0||P.dash>0){boss.hp-=1+up(9)*.12;score+=1000*combo;combo=Math.min(35,combo+1);burst(boss.x,340,10,'violet');if(boss.hp<=0){boss=null;runGems+=35;save.stats.boss++;pop(1000,180,'GUARDIAN DEFEATED','gold');burst(1000,250,55,'gold')}}else hit()}}
function update(dt){time+=dt;const speed=Math.min(1100,(430+time*7+combo*3)*WORLDS[world][3]);energy=Math.min(maxEnergy,energy+dt*12);P.attack=Math.max(0,P.attack-dt);P.dash=Math.max(0,P.dash-dt);P.parry=Math.max(0,P.parry-dt);P.inv=Math.max(0,P.inv-dt);P.x+=(LANES[P.lane]-P.x)*Math.min(1,dt*16);P.vy+=2300*dt;P.y+=P.vy*dt;if(P.y<=0){P.y=0;P.vy=0;P.jumps=0}spawn-=dt;if(spawn<=0){pattern();spawn=Math.max(.27,.82-time*.002)}if(!boss&&time>18&&Math.random()<.0025)bossStart();for(let i=objects.length-1;i>=0;i--){const o=objects[i];o.x-=speed*dt;o.cool=Math.max(0,o.cool-dt);o.rot+=dt*3;o.phase+=dt;if(o.type==='air'||o.type==='drone')o.y+=Math.sin(o.phase*3)*dt*18;if(o.x<-220){objects.splice(i,1);continue}collide(o)}bossUpdate(dt,speed);if(combo>1)combo=Math.max(1,combo-dt*.06);score+=dt*speed*.04*combo*scoreMult();shake=Math.max(0,shake-dt*25);for(const d of dust){d.x-=speed*dt*d.s*.02;if(d.x<0)d.x=W;d.y+=Math.sin(time+d.x)*.03}hud()}
function burst(x,y,n,type){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*560,vy:(Math.random()-.8)*450,l:.45+Math.random()*.65,type,sz:2+Math.random()*5})}function pop(x,y,v,type){texts.push({x,y,v,type,l:1})}
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function mountain(x,y,w,h,c){ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w*.18,y-h*.6);ctx.lineTo(x+w*.36,y);ctx.lineTo(x+w*.55,y-h);ctx.lineTo(x+w*.75,y);ctx.lineTo(x+w*.9,y-h*.5);ctx.lineTo(x+w,y);ctx.lineTo(x+w,G);ctx.lineTo(x,G);ctx.closePath();ctx.fill()}
function scene(){const p=pal[world],g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,p[0]);g.addColorStop(.58,p[1]);g.addColorStop(1,p[2]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const glow=['#55e58c','#ff7043','#67e8ff','#aebdff','#5fffe2','#c98cff'][world];
 ctx.globalAlpha=.85;for(const s of stars){let x=(s.x-time*(6+s.s*5))%W;if(x<0)x+=W;ctx.fillStyle=glow;ctx.globalAlpha=s.a*(world>3?1:.55);ctx.beginPath();ctx.arc(x,s.y,s.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
 const shift=(time*25)%W;mountain(-shift,G-180,W+400,210,p[1]);mountain(-shift*.45,G-120,W+400,150,p[0]);
 ctx.globalAlpha=.22;for(let i=0;i<8;i++){ctx.fillStyle=glow;ctx.beginPath();ctx.arc(((i*230-shift*1.8)%W+W)%W,250+(i%3)*55,55+(i%2)*35,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
 if(world===0){for(let i=0;i<10;i++){let x=((i*180-shift*.7)%W+W)%W;ctx.fillStyle='#071f17';ctx.fillRect(x,G-140-(i%3)*25,24,140);ctx.beginPath();ctx.arc(x+12,G-150-(i%3)*25,55,0,Math.PI*2);ctx.fill()}}
 if(world===1){for(let i=0;i<7;i++){let x=((i*250-shift)%W+W)%W;ctx.fillStyle='#ff8a3d';ctx.globalAlpha=.3;ctx.beginPath();ctx.arc(x,G-120-(i%2)*45,42,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}}
 if(world===2){for(let i=0;i<18;i++){let x=((i*97-time*50)%W+W)%W;ctx.fillStyle='#dff8ff';ctx.globalAlpha=.45;ctx.fillRect(x,130+(i*41)%390,2,15);ctx.globalAlpha=1}}
 if(world===3){for(let i=0;i<6;i++){let x=((i*290-shift)%W+W)%W;ctx.strokeStyle='#aebdff';ctx.globalAlpha=.35;ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(x,120);ctx.lineTo(x+90,180);ctx.lineTo(x+180,120);ctx.stroke();ctx.globalAlpha=1}}
 if(world===4){ctx.globalAlpha=.3;for(let i=0;i<12;i++){let x=((i*150-time*100)%W+W)%W;ctx.fillStyle='#00e6cf';ctx.fillRect(x,100+(i%5)*70,80,4);ctx.fillStyle='#ff38dc';ctx.fillRect(x+35,130+(i%4)*80,45,3)}ctx.globalAlpha=1}
 if(world===5){ctx.globalAlpha=.8;for(let i=0;i<55;i++){let a=i*.77+time*.15,r=90+(i%10)*32;let x=W/2+Math.cos(a)*r,y=250+Math.sin(a)*r*.5;ctx.fillStyle=i%2?'#c98cff':'#67e8ff';ctx.fillRect(x,y,2,2)}ctx.globalAlpha=1}
 ctx.fillStyle='#02070c';ctx.globalAlpha=.35;ctx.fillRect(0,G-4,W,4);ctx.globalAlpha=1;ctx.fillStyle='#0a1118';ctx.fillRect(0,G,W,H-G);
 ctx.globalAlpha=.28;ctx.strokeStyle=glow;ctx.lineWidth=2;for(let i=0;i<12;i++){let x=((i*150-time*80)%W+W)%W;ctx.beginPath();ctx.moveTo(x,G);ctx.lineTo(x-70,G+H-G);ctx.stroke()}ctx.globalAlpha=1;
 for(const d of dust){ctx.fillStyle=glow;ctx.globalAlpha=.12;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function drawDino(x,y,s,scale=1,alpha=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.globalAlpha=alpha;ctx.shadowBlur=24;ctx.shadowColor=s[2];
 ctx.fillStyle=s[2];roundedRect(-30,-76,58,74,18);ctx.fill();ctx.beginPath();ctx.ellipse(27,-94,40,31,-.08,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(48,-103);ctx.lineTo(86,-90);ctx.lineTo(50,-78);ctx.closePath();ctx.fill();
 ctx.fillStyle='#07131a';ctx.beginPath();ctx.arc(45,-102,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(46,-103,2,0,Math.PI*2);ctx.fill();
 ctx.fillStyle=s[2];ctx.fillRect(-23,-10,15,43);ctx.fillRect(12,-10,15,43);ctx.strokeStyle=s[2];ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-26,-58);ctx.lineTo(-67,-37);ctx.lineTo(-92,-52);ctx.stroke();
 ctx.fillStyle='#ffffff55';ctx.beginPath();ctx.moveTo(-20,-70);ctx.lineTo(-7,-70);ctx.lineTo(-18,-20);ctx.closePath();ctx.fill();ctx.restore()}
function player(){const s=SKINS[save.skin]||SKINS[0],y=G-P.y;drawDino(P.x,y,s,1,P.inv&&Math.floor(P.inv*22)%2===0?.35:1);ctx.save();ctx.translate(P.x,y);if(P.dash){ctx.strokeStyle=s[2];ctx.globalAlpha=.35;ctx.lineWidth=18;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(-80-i*25,-55);ctx.lineTo(-170-i*30,-55);ctx.stroke()}}if(P.attack){ctx.strokeStyle='#fff';ctx.shadowBlur=20;ctx.shadowColor=s[2];ctx.lineWidth=10;ctx.beginPath();ctx.arc(42,-65,72,-1.15,1.05);ctx.stroke()}if(P.parry){ctx.strokeStyle='#ffe77a';ctx.shadowBlur=25;ctx.shadowColor='#ffe77a';ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,-65,78,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function enemyArt(o){const c={meteor:'#ff6347',crystal:'#ff7de3',gem:'#5fffe2',air:'#d8f6ff',drone:'#ffe36e',elite:'#ffbf52',spike:'#ff647c',rock:'#6b8b82',enemy:'#ff806b'}[o.type];ctx.shadowBlur=22;ctx.shadowColor=c;ctx.fillStyle=c;
 if(o.type==='meteor'){ctx.beginPath();ctx.moveTo(-42,28);ctx.lineTo(-14,-28);ctx.lineTo(8,-42);ctx.lineTo(39,-18);ctx.lineTo(27,30);ctx.closePath();ctx.fill();ctx.fillStyle='#7d170e';ctx.beginPath();ctx.arc(-10,5,8,0,7);ctx.arc(15,-12,5,0,7);ctx.fill();return}
 if(o.type==='spike'){ctx.beginPath();ctx.moveTo(-42,28);ctx.lineTo(-22,-25);ctx.lineTo(0,18);ctx.lineTo(22,-39);ctx.lineTo(43,28);ctx.closePath();ctx.fill();return}
 if(o.type==='gem'||o.type==='crystal'){ctx.rotate(Math.PI/4);ctx.fillRect(-18,-18,36,36);ctx.fillStyle='#ffffff88';ctx.fillRect(-12,-12,7,7);return}
 if(o.type==='rock'){ctx.beginPath();ctx.moveTo(-35,25);ctx.lineTo(-28,-20);ctx.lineTo(-5,-35);ctx.lineTo(30,-22);ctx.lineTo(38,24);ctx.closePath();ctx.fill();return}
 ctx.beginPath();ctx.ellipse(0,0,o.w*.44,o.h*.43,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111522';ctx.beginPath();ctx.arc(-14,-8,6,0,7);ctx.arc(14,-8,6,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-12,-10,2,0,7);ctx.arc(16,-10,2,0,7);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-25,20);ctx.lineTo(-48,38);ctx.moveTo(25,20);ctx.lineTo(48,38);ctx.stroke();
 if(o.type==='elite'){ctx.strokeStyle='#fff2a8';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,55,0,Math.PI*2);ctx.stroke();ctx.font='28px Arial';ctx.fillText('◆',-11,-52)}}
function objectsDraw(){for(const o of objects){if(o.dead)continue;ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.rot*.25);enemyArt(o);ctx.restore()}if(boss){ctx.save();ctx.translate(boss.x,340+Math.sin(boss.phase*2)*12);ctx.shadowBlur=45;ctx.shadowColor='#c98cff';ctx.fillStyle='#c98cff';ctx.beginPath();ctx.ellipse(0,0,105,118,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#21152d';ctx.beginPath();ctx.arc(-35,-20,13,0,7);ctx.arc(35,-20,13,0,7);ctx.fill();ctx.fillStyle='#ffe77a';ctx.font='48px Arial';ctx.fillText('👑',-24,-110);ctx.strokeStyle='#ffffff55';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,128,0,Math.PI*2);ctx.stroke();ctx.restore()}}
function hud(){if($('health'))$('health').textContent='●'.repeat(Math.max(0,hp))+'○'.repeat(Math.max(0,maxHp-hp));if($('energyText'))$('energyText').textContent=Math.floor(energy);if($('score'))$('score').textContent=Math.floor(score).toLocaleString();if($('combo'))$('combo').textContent='x'+combo.toFixed(1);if($('gems'))$('gems').textContent=(save.gems+Math.floor(runGems*gemMult())).toLocaleString();if($('guardianHud'))$('guardianHud').textContent=boss?'BOSS':'RUN';if($('energyBar'))$('energyBar').style.width=(energy/maxEnergy*100)+'%';if($('rageBar'))$('rageBar').style.width=rage+'%';if($('bossBar'))$('bossBar').style.width=boss?(boss.hp/boss.max*100)+'%':'0%';if($('bestScore'))$('bestScore').textContent=save.best.toLocaleString();if($('rank'))$('rank').textContent=save.best>=110000?'DIVINE':save.best>=70000?'MYTHIC':save.best>=42000?'LEGEND':save.best>=22000?'ELITE':save.best>=9000?'HUNTER':'ROOKIE'}
function draw(){ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);scene();objectsDraw();for(const p of particles){p.x+=p.vx/60;p.y+=p.vy/60;p.l-=.016;ctx.globalAlpha=Math.max(0,p.l);ctx.fillStyle=p.type==='gold'?'#ffe77a':p.type==='violet'?'#c98cff':p.type==='red'?'#ff647c':'#5fffe2';ctx.beginPath();ctx.arc(p.x,p.y,p.sz,0,Math.PI*2);ctx.fill()}for(let i=particles.length-1;i>=0;i--)if(particles[i].l<=0)particles.splice(i,1);ctx.globalAlpha=1;player();for(const t of texts){t.y-=.7;t.l-=.02;ctx.globalAlpha=Math.max(0,t.l);ctx.fillStyle=t.type==='gold'?'#ffe77a':t.type==='red'?'#ff647c':'#fff';ctx.font='900 22px Arial';ctx.textAlign='center';ctx.shadowBlur=12;ctx.shadowColor=ctx.fillStyle;ctx.fillText(t.v,t.x,t.y)}for(let i=texts.length-1;i>=0;i--)if(texts[i].l<=0)texts.splice(i,1);ctx.globalAlpha=1;ctx.restore()}
function loop(now){if(!running)return;if(!paused){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw()}else last=now;requestAnimationFrame(loop)}
$('codeInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('redeemButton')?.click()});$('redeemButton')?.addEventListener('click',()=>{const input=$('codeInput'),msg=$('codeMessage'),code=(input?.value||'').trim().toUpperCase(),rewards={DINO100:100,LEGEND500:500,MYTHIC50K:50000,LEGENDARY1M:1000000,TRILLION1:1000000000000};if(!code){msg.textContent='ENTER A CODE';return}if(save.used?.includes(code)){msg.textContent='ALREADY REDEEMED';return}if(rewards[code]){save.gems+=rewards[code];save.used=[...(save.used||[]),code];persist();msg.textContent='REWARD ADDED: '+rewards[code].toLocaleString()+' GEMS';render();hud()}else msg.textContent='INVALID CODE'});render();hud();
})();