(()=>{
'use strict';
const $=id=>document.getElementById(id), canvas=$('gameCanvas'); if(!canvas)return;
const ctx=canvas.getContext('2d'); if(!ctx)return;
const W=1440,H=760,G=590,LANES=[350,720,1090],SAVE='DINO_LEGENDS_V24';
const SKINS=[
 ['Verdant Rex','🌿','#55e58c','NATURE','RARE'],['Ember Fang','🔥','#ff7043','FIRE','RARE'],['Frost Claw','❄️','#67e8ff','ICE','RARE'],['Volt Raptor','⚡','#ffe05c','STORM','EPIC'],
 ['Void Stalker','🌑','#b477ff','VOID','EPIC'],['Solar Tyrant','☀️','#ffd45c','SOLAR','EPIC'],['Crystal Drake','💎','#ff7de3','CRYSTAL','EPIC'],['Toxic Hunter','☣️','#a8ff57','TOXIC','LEGENDARY'],
 ['Cyber Rex','🤖','#35dcff','CYBER','LEGENDARY'],['Shadow Warden','🗡️','#d18cff','SHADOW','LEGENDARY'],['Ocean Leviathan','🌊','#55aaff','OCEAN','LEGENDARY'],['Lava Colossus','🌋','#ff594d','MAGMA','LEGENDARY'],
 ['Thunder King','🌩️','#aebdff','THUNDER','MYTHIC'],['Moon Beast','🌙','#c8b7ff','MOON','MYTHIC'],['Star Eater','✨','#ffe58a','COSMIC','MYTHIC'],['Bloodmoon Rex','🩸','#ff6c86','BLOOD','MYTHIC'],
 ['Ancient Guardian','🗿','#d0a77a','ANCIENT','DIVINE'],['Neon Phantom','💠','#5fffe2','NEON','DIVINE'],['Chrono Dragon','⏳','#9bb6ff','CHRONO','DIVINE'],['Galaxy Emperor','🌌','#c98cff','GALAXY','DIVINE'],
 ['Omega Titan','⚔️','#ffffff','OMEGA','DIVINE'],['Prism Overlord','🔷','#ff9eea','PRISM','DIVINE'],['Inferno Prime','🔥','#ffb347','PRIME','DIVINE'],['Dino Legend','👑','#ffe77a','LEGEND','DIVINE']
];
const WORLDS=[['Emerald Jungle','🌿',0,1.00],['Ashen Volcano','🌋',9000,1.10],['Frozen Expanse','❄️',22000,.96],['Sky Citadel','🏛️',42000,1.06],['Neon Abyss','💠',70000,1.15],['Cosmic Rift','🌌',110000,1.24]];
const UP=[['Vital Core','❤️','+1 maximum HP',700],['Energy Reactor','⚡','+20 maximum energy',1000],['Dash Drive','💨','-5 dash energy cost',1300],['Combo Engine','🔥','+10% combo score',1800],['Gem Magnet','🧲','+25% run gems',2200],['Parry Matrix','🛡️','+0.10s parry window',2700],['Rage Reactor','☄️','+20% rage gain',3200],['Lucky Core','🍀','better rare-event odds',3900],['Hunter Protocol','🎯','+8% enemy score',4600],['Guardian Core','👑','+12% boss damage',5500]];
const MISS=[['Combo Architect','Reach x12 combo',12,'combo'],['Gem Rush','Collect 40 run gems',40,'gems'],['Air Hunter','Defeat 20 airborne enemies',20,'air'],['Elite Breaker','Defeat 25 elites',25,'elite'],['Perfect Guard','Land 12 perfect parries',12,'parry'],['Guardian Hunter','Defeat 4 guardians',4,'boss'],['Long Haul','Survive 150 seconds',150,'time'],['Explorer','Unlock 4 worlds',4,'world']];
const D={gems:2500,best:0,skin:0,owned:[0],up:{},world:0,missions:{},stats:{gems:0,air:0,elite:0,parry:0,boss:0,time:0}};
function clone(o){return JSON.parse(JSON.stringify(o))} function load(){try{const v=JSON.parse(localStorage.getItem(SAVE));return {...clone(D),...v,owned:Array.isArray(v.owned)?[...new Set(v.owned)]:[0],up:v.up||{},missions:v.missions||{},stats:{...D.stats,...(v.stats||{})}}}catch{return clone(D)}}
let save=load();const persist=()=>localStorage.setItem(SAVE,JSON.stringify(save));
let running=false,paused=false,last=0,time=0,score=0,runGems=0,hp=3,maxHp=3,energy=100,maxEnergy=100,rage=0,combo=1,peak=1,world=save.world||0,spawn=.5,boss=null,objects=[],particles=[],texts=[],shake=0;
const P={lane:1,x:720,y:0,vy:0,jumps:0,attack:0,dash:0,parry:0,inv:0};
const up=i=>Number(save.up[i]||0), gemMult=()=>1+up(4)*.25, scoreMult=()=>1+up(3)*.10+up(8)*.08, dashCost=()=>Math.max(12,34-up(2)*5), parryWindow=()=>.28+up(5)*.1, rageMult=()=>1+up(6)*.2;
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)} addEventListener('resize',resize,{passive:true});resize();
function panel(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id))} document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>panel(b.dataset.panel));
function esc(s){return String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function render(){
 const s=$('skins');if(s)s.innerHTML=`<div class="heading"><div><small>LEGEND VAULT · ${save.owned.length}/${SKINS.length} COLLECTED</small><h2>SKIN FORGE</h2></div><b>${save.gems.toLocaleString()} GEMS</b></div><div class="grid skinGrid">${SKINS.map((v,i)=>{const owned=save.owned.includes(i),active=save.skin===i,price=i===0?0:Math.floor(1200*Math.pow(1.34,i));return `<article class="item skinCard ${active?'selected':''}" style="--glow:${v[2]}"><div class="skinPreview"><div class="aura"></div><div class="dinoGlyph">🦖</div><b>${v[1]}</b></div><div class="skinTags"><span>${v[4]}</span><span>${v[3]}</span></div><h3>${esc(v[0])}</h3><small>UNIQUE SILHOUETTE · AURA · TRAIL</small><div class="skinStats"><i>⚡ ${100+i%8*3}</i><i>🛡 ${100+i%6*4}</i><i>✦ ${100+i%7*5}</i></div><footer><span class="price">${owned?(active?'EQUIPPED':'OWNED'):price.toLocaleString()+' GEMS'}</span><button class="action skinBtn" data-i="${i}" ${!owned&&save.gems<price?'disabled':''}>${owned?(active?'EQUIPPED':'EQUIP'):'UNLOCK'}</button></footer></article>`}).join('')}</div>`;
 const a=$('abilities');if(a)a.innerHTML=`<div class="heading"><div><small>10 SYSTEMS · 5 LEVELS EACH</small><h2>UPGRADE LAB</h2></div><b>${Object.values(save.up).reduce((x,y)=>x+Number(y||0),0)} LEVELS</b></div><div class="grid">${UP.map((u,i)=>{let lv=Math.min(5,up(i)),cost=Math.floor(u[3]*Math.pow(1.58,lv));return `<article class="item upgradeCard"><div class="icon">${u[1]}</div><h3>${u[0]}</h3><small>LEVEL ${lv}/5</small><p>${u[2]}</p><div class="levelDots">${[0,1,2,3,4].map(n=>`<i class="${n<lv?'on':''}"></i>`).join('')}</div><footer><span class="price">${lv>=5?'MAX':cost.toLocaleString()+' GEMS'}</span><button class="action upBtn" data-i="${i}" ${lv>=5||save.gems<cost?'disabled':''}>${lv>=5?'MAX':'UPGRADE'}</button></footer></article>`}).join('')}</div>`;
 const m=$('missions');if(m)m.innerHTML=`<div class="heading"><div><small>REWARD TRACK</small><h2>MISSIONS</h2></div></div>${MISS.map((q,i)=>{const v=missionValue(i),done=!!save.missions[i],reward=(i+1)*900;return `<div class="mission"><span><b>${q[0]}</b><small>${q[1]} · ${Math.min(q[2],v)}/${q[2]}</small></span><button class="action missBtn" data-i="${i}" ${done||v<q[2]?'disabled':''}>${done?'CLAIMED':'CLAIM '+reward}</button></div>`}).join('')}`;
 const w=$('worlds');if(w)w.innerHTML=`<div class="heading"><div><small>EXPEDITION NETWORK · ${world+1}/${WORLDS.length}</small><h2>WORLDS</h2></div></div><div class="grid">${WORLDS.map((q,i)=>`<article class="item worldCard ${save.world<i?'locked':''}" style="--glow:${['#55e58c','#ff7043','#67e8ff','#aebdff','#5fffe2','#c98cff'][i]}"><div class="worldIcon">${q[1]}</div><h3>${q[0]}</h3><small>${save.world>=i?'UNLOCKED':'BEST SCORE '+q[2].toLocaleString()}</small><p>Speed ×${q[3].toFixed(2)} · evolving hazards · unique atmosphere.</p><footer><button class="action worldBtn" data-i="${i}" ${save.world<i?'disabled':''}>${world===i?'ACTIVE':'ENTER'}</button></footer></article>`).join('')}</div>`;
 document.querySelectorAll('.skinBtn').forEach(b=>b.onclick=()=>buySkin(+b.dataset.i));document.querySelectorAll('.upBtn').forEach(b=>b.onclick=()=>buyUp(+b.dataset.i));document.querySelectorAll('.worldBtn').forEach(b=>b.onclick=()=>{world=+b.dataset.i;render();hud()});document.querySelectorAll('.missBtn').forEach(b=>b.onclick=()=>claim(+b.dataset.i));
}
function buySkin(i){const price=i?Math.floor(1200*Math.pow(1.34,i)):0;if(save.owned.includes(i))save.skin=i;else if(save.gems>=price){save.gems-=price;save.owned.push(i);save.skin=i}else return;persist();render();hud()}
function buyUp(i){const lv=up(i);if(lv>=5)return;const cost=Math.floor(UP[i][3]*Math.pow(1.58,lv));if(save.gems<cost)return;save.gems-=cost;save.up[i]=lv+1;persist();render();hud()}
function missionValue(i){const st=save.stats;return [peak,st.gems,st.air,st.elite,st.parry,st.boss,Math.floor(st.time),save.world+1][i]}
function claim(i){if(save.missions[i]||missionValue(i)<MISS[i][2])return;save.missions[i]=1;save.gems+=(i+1)*900;persist();render();hud()}
function start(){running=true;paused=false;time=0;score=0;runGems=0;maxHp=3+up(0);hp=maxHp;maxEnergy=100+up(1)*20;energy=maxEnergy;rage=0;combo=1;peak=1;spawn=.45;boss=null;objects=[];particles=[];texts=[];shake=0;Object.assign(P,{lane:1,x:720,y:0,vy:0,jumps:0,attack:0,dash:0,parry:0,inv:0});save.stats.runs=(save.stats.runs||0)+1;persist();$('startScreen')?.classList.add('hidden');$('gameOverScreen')?.classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function finish(){if(!running)return;running=false;const final=Math.floor(score),reward=Math.floor(runGems*gemMult());save.best=Math.max(save.best,final);save.gems+=reward;save.stats.gems+=runGems;save.stats.time+=time;while(save.world<WORLDS.length-1&&save.best>=WORLDS[save.world+1][2])save.world++;persist();render();$('finalScore').textContent=final.toLocaleString();$('finalStats').textContent=`${WORLDS[world][0]} · PEAK x${peak.toFixed(1)} · +${reward.toLocaleString()} GEMS`;$('gameOverScreen')?.classList.remove('hidden');hud()}
function act(a){if(!running||paused)return;if(a==='left')P.lane=Math.max(0,P.lane-1);if(a==='right')P.lane=Math.min(2,P.lane+1);if(a==='jump'&&P.jumps<2){P.vy=P.jumps?-790:-960;P.jumps++;burst(P.x,G-P.y,9,'cyan')}if(a==='attack')P.attack=.24;if(a==='dash'&&energy>=dashCost()){energy-=dashCost();P.dash=.34;P.inv=.48;burst(P.x,G-P.y,18,'gold')}if(a==='parry'&&energy>=20){energy-=20;P.parry=parryWindow()}if(a==='rage'&&rage>=100){rage=0;score+=2400*combo;combo=Math.min(35,combo+3);burst(P.x,G-P.y,28,'violet')}}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();act(b.dataset.action)}));addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft'||e.code==='KeyA')act('left');else if(e.code==='ArrowRight'||e.code==='KeyD')act('right');else if(e.code==='Space'||e.code==='ArrowUp')act('jump');else if(e.code==='KeyF')act('attack');else if(e.code==='ShiftLeft'||e.code==='ShiftRight')act('dash');else if(e.code==='KeyS')act('parry');else if(e.code==='KeyR')act('rage');else if(e.code==='Escape'&&running){paused=!paused;$('pauseScreen')?.classList.toggle('hidden',!paused);last=performance.now()}else if(e.code==='Enter'&&!running)start()});$('startButton')?.addEventListener('click',start);$('restartButton')?.addEventListener('click',start);$('resumeButton')?.addEventListener('click',()=>{paused=false;$('pauseScreen')?.classList.add('hidden');last=performance.now()});
function spawnObj(type,lane,x=W+80){const spec={rock:[72,65,G-30],spike:[72,45,G-12],enemy:[70,78,G-42],elite:[88,92,G-50],air:[74,48,390],gem:[34,34,G-125],meteor:[92,54,320],crystal:[42,55,G-165],drone:[70,48,300]}[type];if(spec)objects.push({type,lane,x,w:spec[0],h:spec[1],y:spec[2],hp:type==='elite'?2:1,cool:0,dead:false,rot:0})}
function pattern(){const r=Math.random(),l=Math.floor(Math.random()*3),rare=.08+up(7)*.035;if(time<5){spawnObj(r<.75?'rock':'gem',l);return}if(r<rare){spawnObj('meteor',l);spawnObj('crystal',(l+1)%3,W+230)}else if(r<.25){spawnObj('enemy',l);spawnObj('air',(l+1)%3,W+220)}else if(r<.43){spawnObj('spike',l);spawnObj('rock',(l+1)%3,W+190)}else if(r<.58){spawnObj('elite',l)}else if(r<.72){spawnObj('air',l);spawnObj('gem',(l+2)%3,W+190)}else{spawnObj('drone',l);spawnObj('spike',(l+2)%3,W+250)}}
function hit(){if(P.inv>0)return;if(P.parry>0){score+=700*combo;combo=Math.min(35,combo+1.8);peak=Math.max(peak,combo);rage=Math.min(100,rage+10*rageMult());P.parry=0;save.stats.parry++;pop(P.x,G-120,'PERFECT PARRY','gold');return}hp--;combo=1;P.inv=1;shake=10;pop(P.x,G-100,'HIT','red');if(hp<=0)finish()}
function defeat(o){o.hp--;if(o.hp>0)return;o.dead=true;const elite=o.type==='elite';if(o.type==='air')save.stats.air++;if(elite)save.stats.elite++;runGems+=elite?5:(o.type==='crystal'?3:1);score+=(elite?1100:340)*combo*scoreMult();combo=Math.min(35,combo+(elite?1.2:.72));peak=Math.max(peak,combo);rage=Math.min(100,rage+7*rageMult());burst(o.x,o.y,18,'gold');pop(o.x,o.y-25,'KO','cyan')}
function collide(o){if(o.dead||o.cool>0||o.lane!==P.lane||Math.abs(o.x-P.x)>o.w*.55+32)return;o.cool=.16;if(['gem','crystal'].includes(o.type)){o.dead=true;runGems+=o.type==='crystal'?3:1;score+=400*combo;combo=Math.min(35,combo+.35);peak=Math.max(peak,combo);return}if(o.type==='air'||o.type==='drone'){if(P.y>70||P.dash>0||P.attack>0)defeat(o);else hit();return}if(P.attack>0||P.dash>0)defeat(o);else if(P.y>90){o.dead=true;score+=250*combo;combo=Math.min(35,combo+.5);peak=Math.max(peak,combo)}else hit()}
function bossStart(){if(boss)return;boss={x:1190,hp:24,max:24,cool:.7};pop(720,160,'GUARDIAN INCOMING','gold');burst(720,300,35,'violet')}
function bossUpdate(dt,speed){if(!boss)return;boss.x=Math.max(920,boss.x-speed*.18*dt);boss.cool-=dt;if(boss.cool<=0){boss.cool=.65+Math.random()*.6;const l=Math.floor(Math.random()*3);spawnObj('meteor',l,W+120);spawnObj('air',(l+1)%3,W+260)}if(Math.abs(boss.x-P.x)<150&&P.lane===1){if(P.attack>0||P.dash>0){boss.hp-=1+up(9)*.12;score+=1000*combo;combo=Math.min(35,combo+1);if(boss.hp<=0){boss=null;runGems+=35;save.stats.boss++;pop(1000,180,'GUARDIAN DEFEATED','gold');burst(1000,250,40,'gold')}}else hit()}}
function update(dt){time+=dt;const speed=Math.min(1100,(430+time*7+combo*3)*WORLDS[world][3]);energy=Math.min(maxEnergy,energy+dt*12);P.attack=Math.max(0,P.attack-dt);P.dash=Math.max(0,P.dash-dt);P.parry=Math.max(0,P.parry-dt);P.inv=Math.max(0,P.inv-dt);P.x+=(LANES[P.lane]-P.x)*Math.min(1,dt*16);P.vy+=2300*dt;P.y+=P.vy*dt;if(P.y<=0){P.y=0;P.vy=0;P.jumps=0}spawn-=dt;if(spawn<=0){pattern();spawn=Math.max(.27,.82-time*.002)}if(!boss&&time>18&&Math.random()<.0025)bossStart();for(let i=objects.length-1;i>=0;i--){const o=objects[i];o.x-=speed*dt;o.cool=Math.max(0,o.cool-dt);o.rot+=dt*3;if(o.x<-220){objects.splice(i,1);continue}collide(o)}bossUpdate(dt,speed);if(combo>1)combo=Math.max(1,combo-dt*.06);score+=dt*speed*.04*combo*scoreMult();shake=Math.max(0,shake-dt*25);hud()}
function burst(x,y,n,type){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*560,vy:(Math.random()-.8)*450,l:.45+Math.random()*.65,type})}function pop(x,y,v,type){texts.push({x,y,v,type,l:1})}
function scene(){const palettes=[['#061c24','#062b20'],['#260b08','#5b1b0d'],['#10233e','#b9ddff'],['#161339','#28204e'],['#031b24','#07101c'],['#10071e','#2d1248']][world];let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,palettes[0]);g.addColorStop(1,palettes[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const glow=['#55e58c','#ff7043','#67e8ff','#aebdff','#5fffe2','#c98cff'][world];ctx.globalAlpha=.18;for(let i=0;i<7;i++){ctx.fillStyle=glow;ctx.beginPath();ctx.arc((i*260-time*speedSafe())%W,150+(i%3)*80,80+(i%2)*70,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle=palettes[1];ctx.fillRect(0,G,W,H);ctx.fillStyle='#ffffff10';for(let i=0;i<26;i++){let x=(i*113-time*speedSafe()*.12)%W;if(x<0)x+=W;ctx.fillRect(x,G-60-(i%4)*20,3,60+(i%4)*20)}}function speedSafe(){return 70}
function player(){const s=SKINS[save.skin]||SKINS[0],y=G-P.y;ctx.save();ctx.translate(P.x,y);if(P.inv&&Math.floor(P.inv*22)%2===0)ctx.globalAlpha=.35;ctx.shadowBlur=P.dash?38:20;ctx.shadowColor=s[2];ctx.fillStyle=s[2];ctx.beginPath();ctx.ellipse(0,-46,35,48,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(29,-84,36,30,-.08,0,Math.PI*2);ctx.fill();ctx.fillStyle='#08141b';ctx.beginPath();ctx.arc(44,-89,5,0,Math.PI*2);ctx.fill();ctx.fillStyle=s[2];ctx.fillRect(-26,-7,13,42);ctx.fillRect(13,-7,13,42);ctx.strokeStyle=s[2];ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-28,-55);ctx.lineTo(-67,-35);ctx.lineTo(-93,-52);ctx.stroke();ctx.globalAlpha=.9;ctx.font='25px Arial';ctx.fillText(s[1],-13,-122);if(P.attack){ctx.strokeStyle='#fff';ctx.lineWidth=9;ctx.beginPath();ctx.arc(48,-55,64,-1.2,1.1);ctx.stroke()}if(P.parry){ctx.strokeStyle='#ffe77a';ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,-55,67,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function objectsDraw(){for(const o of objects){if(o.dead)continue;ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.rot);const c={meteor:'#ff6347',crystal:'#ff7de3',gem:'#5fffe2',air:'#d8f6ff',drone:'#ffe36e',elite:'#ffbf52',spike:'#ff647c',rock:'#6b8b82',enemy:'#ff806b'}[o.type];ctx.fillStyle=c;ctx.shadowBlur=18;ctx.shadowColor=c;if(['spike','meteor'].includes(o.type)){ctx.beginPath();ctx.moveTo(-38,32);ctx.lineTo(0,-35);ctx.lineTo(38,32);ctx.closePath();ctx.fill()}else if(['gem','crystal'].includes(o.type)){ctx.rotate(Math.PI/4);ctx.fillRect(-16,-16,32,32)}else{ctx.beginPath();ctx.ellipse(0,0,o.w*.43,o.h*.43,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#07131a';ctx.fillRect(-12,-8,7,7);ctx.fillRect(8,-8,7,7)}ctx.restore()}if(boss){ctx.save();ctx.translate(boss.x,340);ctx.fillStyle='#c98cff';ctx.shadowBlur=35;ctx.shadowColor='#c98cff';ctx.beginPath();ctx.arc(0,0,88,0,Math.PI*2);ctx.fill();ctx.fillStyle='#171022';ctx.beginPath();ctx.arc(-28,-18,10,0,Math.PI*2);ctx.arc(28,-18,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffd45c';ctx.font='35px Arial';ctx.fillText('👑',-18,-90);ctx.restore()}}
function hud(){if($('health'))$('health').textContent='●'.repeat(Math.max(0,hp))+'○'.repeat(Math.max(0,maxHp-hp));if($('energyText'))$('energyText').textContent=Math.floor(energy);if($('score'))$('score').textContent=Math.floor(score).toLocaleString();if($('combo'))$('combo').textContent='x'+combo.toFixed(1);if($('gems'))$('gems').textContent=(save.gems+Math.floor(runGems*gemMult())).toLocaleString();if($('guardianHud'))$('guardianHud').textContent=boss?'BOSS':'RUN';if($('energyBar'))$('energyBar').style.width=(energy/maxEnergy*100)+'%';if($('rageBar'))$('rageBar').style.width=rage+'%';if($('bossBar'))$('bossBar').style.width=boss?(boss.hp/boss.max*100)+'%':'0%';if($('bestScore'))$('bestScore').textContent=save.best.toLocaleString();if($('rank'))$('rank').textContent=save.best>=110000?'DIVINE':save.best>=70000?'MYTHIC':save.best>=42000?'LEGEND':save.best>=22000?'ELITE':save.best>=9000?'HUNTER':'ROOKIE'}
function draw(){ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);scene();objectsDraw();for(const p of particles){p.x+=p.vx/60;p.y+=p.vy/60;p.l-=.016;ctx.globalAlpha=Math.max(0,p.l);ctx.fillStyle=p.type==='gold'?'#ffe77a':p.type==='violet'?'#c98cff':p.type==='red'?'#ff647c':'#5fffe2';ctx.fillRect(p.x,p.y,5,5)}for(let i=particles.length-1;i>=0;i--)if(particles[i].l<=0)particles.splice(i,1);ctx.globalAlpha=1;player();for(const t of texts){t.y-=.7;t.l-=.02;ctx.globalAlpha=Math.max(0,t.l);ctx.fillStyle=t.type==='gold'?'#ffe77a':t.type==='red'?'#ff647c':'#fff';ctx.font='900 22px Arial';ctx.textAlign='center';ctx.fillText(t.v,t.x,t.y)}for(let i=texts.length-1;i>=0;i--)if(texts[i].l<=0)texts.splice(i,1);ctx.globalAlpha=1;ctx.restore()}
function loop(now){if(!running)return;if(!paused){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw()}else last=now;requestAnimationFrame(loop)}
$('codeInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('redeemButton')?.click()});$('redeemButton')?.addEventListener('click',()=>{const input=$('codeInput'),msg=$('codeMessage'),code=(input?.value||'').trim().toUpperCase(),rewards={DINO100:100,LEGEND500:500,MYTHIC50K:50000,LEGENDARY1M:1000000,TRILLION1:1000000000000};if(!code){msg.textContent='ENTER A CODE';return}if(save.used?.includes(code)){msg.textContent='ALREADY REDEEMED';return}if(rewards[code]){save.gems+=rewards[code];save.used=[...(save.used||[]),code];persist();msg.textContent='REWARD ADDED: '+rewards[code].toLocaleString()+' GEMS';render();hud()}else msg.textContent='INVALID CODE'});render();hud();
})();