"use strict";
const $=id=>document.getElementById(id);
const canvas=$("gameCanvas"),ctx=canvas.getContext("2d");
const SAVE="DINO_LEGENDS_V10";
const skinData=[
["Arthur Rex","⚔️",0,"LEGENDARY KNIGHT"],["Ghost Rex","👻",500000,"PHANTOM"],["Price Raptor","🎯",900000,"ELITE OPERATIVE"],["Leon Rex","🦁",1500000,"SURVIVOR"],["Agent Rex","🕶️",2500000,"STEALTH"],["Michael Rex","🚗",4000000,"OUTLAW"],["CJ Rex","🏙️",6500000,"STREET KING"],["Cyber Rex","🤖",10000000,"CYBER MYTHIC"],["Samurai Rex","🥷",16000000,"SHADOW WARRIOR"],["Valkyrie Rex","🪽",25000000,"SKY LEGEND"],["Dragon Lord","🐉",40000000,"ANCIENT"],["Demon Rex","😈",65000000,"INFERNAL"],["Ice Emperor","🧊",100000000,"FROSTBORN"],["Storm Emperor","⚡",150000000,"THUNDERBORN"],["Void Emperor","🌌",250000000,"COSMIC"],["Golden Titan","👑",400000000,"ROYAL"],["Neon Phantom","💠",650000000,"NEON"],["Blood Moon Rex","🌑",900000000,"NIGHTMARE"],["Galaxy Rex","🌠",1500000000,"GALACTIC"],["Eternal Dragon","♾️",3000000000,"ETERNAL"]
];
const iconSet=["🐲","🦕","🦖","🐉","👾","🤖","🦄","🌟","☄️","🪐","💀","🪽","🔥","❄️","⚡","🌌","👑","💎","🗿","🎭"];
while(skinData.length<100){const i=skinData.length;const tier=i<35?"EPIC":i<60?"LEGENDARY":i<80?"MYTHIC":"DIVINE";const price=Math.floor(3000000000*Math.pow(1.045,i-19));skinData.push(["Legendary Beast "+(i+1),iconSet[i%iconSet.length],price,tier])}
const skins=skinData;
const base={gems:2500,best:0,skin:0,owned:[0],used:[],runs:0,upgrades:{speed:0,jump:0,shield:0},missions:{run:0,gems:0,jumps:0}};
let save;try{save=JSON.parse(localStorage.getItem(SAVE))||base}catch(e){save=base}save={...base,...save,owned:Array.isArray(save.owned)?save.owned:[0],used:Array.isArray(save.used)?save.used:[],upgrades:{...base.upgrades,...(save.upgrades||{})},missions:{...base.missions,...(save.missions||{})}};
const persist=()=>localStorage.setItem(SAVE,JSON.stringify(save));
const REDEEM_CODES=Object.freeze({TRILLION1:1000000000000,DINO100:100,LEGEND500:500,FANTASY1K:1000,MYTHIC50K:50000,LEGENDARY1M:1000000});
let running=false,score=0,speed=7,health=3,last=0,spawn=0,gemSpawn=0,dashTimer=0,shieldActive=false,combo=1,obs=[],gems=[];
const P={x:150,y:360,w:58,h:70,vy:0,jumps:0};const G=430;
function level(){return Math.max(1,Math.floor(save.best/2500)+1)}
function rank(){const l=level();return l>=40?"MYTHIC":l>=25?"LEGEND":l>=15?"ELITE":l>=5?"HUNTER":"ROOKIE"}
function ui(){if($("gems"))$("gems").textContent=save.gems.toLocaleString();if($("bestScore"))$("bestScore").textContent=Math.floor(save.best).toLocaleString();if($("level"))$("level").textContent=level();if($("score"))$("score").textContent=Math.floor(score).toLocaleString();if($("combo"))$("combo").textContent="x"+combo;if($("health"))$("health").textContent="❤️".repeat(Math.min(8,health))+"🖤".repeat(Math.max(0,Math.min(8,3-health)));if($("profileLevel"))$("profileLevel").textContent=level();if($("profileBest"))$("profileBest").textContent=Math.floor(save.best).toLocaleString();if($("avatar"))$("avatar").textContent=skins[save.skin]?.[1]||"🦖";if($("skinCount"))$("skinCount").textContent=save.owned.length+" / 100";if($("rank"))$("rank").textContent=rank();if($("xpBar")){const p=(save.best%2500)/25;$("xpBar").style.width=Math.min(100,p)+"%"}}
function msg(t){const e=$("codeMessage");if(e)e.textContent=t}
function redeem(){const input=$("codeInput");const code=(input.value||"").trim().toUpperCase();if(!code)return msg("Enter a code first.");if(save.used.includes(code))return msg("❌ This code was already used.");const reward=REDEEM_CODES[code];if(reward===undefined)return msg("❌ Invalid redeem code.");save.gems+=reward;save.used.push(code);persist();ui();input.value="";msg("🎉 Redeemed! +"+reward.toLocaleString()+" gems")}
function renderSkins(){const g=$("skinGrid");if(!g)return;g.innerHTML="";skins.forEach((s,i)=>{const own=save.owned.includes(i),d=document.createElement("article");d.className="item skin-card";d.innerHTML='<div class="icon skin-icon">'+s[1]+'</div><h3>'+s[0]+'</h3><small>'+s[3]+'</small><p>'+(own?'Owned • ready to equip':'Unlock this champion skin')+'</p><footer><span class="price">'+(own?"✓ OWNED":"💎 "+s[2].toLocaleString())+'</span><button class="action">'+(save.skin===i?"EQUIPPED":own?"EQUIP":"UNLOCK")+'</button></footer>';d.querySelector("button").onclick=()=>{if(own){save.skin=i;persist();renderSkins();ui()}else if(save.gems>=s[2]){save.gems-=s[2];save.owned.push(i);save.skin=i;persist();renderSkins();ui()}else msg("❌ Not enough gems")};g.appendChild(d)})}
function renderMissions(){const g=$("missionGrid");if(!g)return;const list=[{id:"run",icon:"🏃",name:"First Adventure",desc:"Start 1 adventure",target:1,reward:500},{id:"gems",icon:"💎",name:"Gem Hunter",desc:"Collect 100 gems",target:100,reward:2500},{id:"jumps",icon:"🪽",name:"Sky Master",desc:"Make 25 jumps",target:25,reward:10000}];g.innerHTML="";list.forEach(m=>{const val=save.missions[m.id]||0,done=val>=m.target;const d=document.createElement("article");d.className="item";d.innerHTML='<div class="icon">'+m.icon+'</div><h3>'+m.name+'</h3><small>MISSION</small><p>'+m.desc+'<br><b>'+Math.min(val,m.target)+' / '+m.target+'</b></p><footer><span class="price">💎 '+m.reward.toLocaleString()+'</span><button class="action" '+(done?'disabled':'')+'>'+(done?'COMPLETED':'IN PROGRESS')+'</button></footer>';g.appendChild(d)})}
function renderWorlds(){const g=$("worldGrid");if(!g)return;const worlds=[['🌲','Enchanted Forest',0,'STARTER'],['🌙','Moonlit Ruins',2500,'LEVEL 5'],['🔥','Dragon Volcano',10000,'LEVEL 10'],['❄️','Frozen Kingdom',25000,'LEVEL 20'],['🌌','Astral Void',100000,'LEVEL 40']];g.innerHTML="";worlds.forEach(w=>{const unlocked=save.best>=w[2],d=document.createElement("article");d.className="item";d.innerHTML='<div class="icon">'+w[0]+'</div><h3>'+w[1]+'</h3><small>'+w[3]+'</small><p>'+(unlocked?'Realm unlocked. Ready for adventure.':'Reach a best score of '+w[2].toLocaleString()+'.')+'</p><footer><span class="price">'+(unlocked?'✓ UNLOCKED':'🔒 LOCKED')+'</span><button class="action" '+(unlocked?'':'disabled')+'>'+(unlocked?'ENTER':'LOCKED')+'</button></footer>';g.appendChild(d)})}
function buyUpgrade(key,name){const prices={speed:1000,jump:1500,shield:2500};const cost=prices[key]*((save.upgrades[key]||0)+1);if(save.gems<cost)return msg("❌ Not enough gems for "+name);save.gems-=cost;save.upgrades[key]++;persist();renderShop();ui()}
function renderShop(){const g=$("shopGrid");if(!g)return;const items=[['speed','⚡','Run Speed','Increase movement speed'],['jump','🪽','Double Jump+','Higher jumps and stronger air control'],['shield','🛡️','Shield Core','Start every run with extra health']];g.innerHTML="";items.forEach(x=>{const lvl=save.upgrades[x[0]]||0,cost={speed:1000,jump:1500,shield:2500}[x[0]]*(lvl+1),d=document.createElement("article");d.className="item";d.innerHTML='<div class="icon">'+x[1]+'</div><h3>'+x[2]+'</h3><small>UPGRADE LEVEL '+lvl+'</small><p>'+x[3]+'</p><footer><span class="price">💎 '+cost.toLocaleString()+'</span><button class="action">UPGRADE</button></footer>';d.querySelector("button").onclick=()=>buyUpgrade(x[0],x[2]);g.appendChild(d)})}
function tabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");const p=$(b.dataset.panel);if(p)p.classList.add("active")})}
function reset(){score=0;speed=7+save.upgrades.speed*.5;health=3+save.upgrades.shield;spawn=0;gemSpawn=0;dashTimer=0;shieldActive=false;combo=1;obs=[];gems=[];P.y=G-P.h;P.vy=0;P.jumps=0}
function start(){reset();running=true;save.runs++;save.missions.run=Math.min(1,save.missions.run+1);persist();$("startScreen")?.classList.add("hidden");$("gameOverScreen")?.classList.add("hidden");last=performance.now();requestAnimationFrame(loop);renderMissions();ui()}
function end(){running=false;save.best=Math.max(save.best,Math.floor(score));persist();if($("finalScore"))$("finalScore").textContent=Math.floor(score).toLocaleString();$("gameOverScreen")?.classList.remove("hidden");renderWorlds();renderMissions();renderShop();ui()}
function jump(){if(!running)return;if(P.jumps<2){P.vy=-(15+save.upgrades.jump*.7);P.jumps++;save.missions.jumps=Math.min(25,save.missions.jumps+1);persist();renderMissions()}}
function dash(){if(!running||dashTimer>0)return;dashTimer=32;score+=75;combo=Math.min(10,combo+1)}
function shield(){if(!running)return;shieldActive=!shieldActive;ui()}
function spawnStuff(dt){spawn+=dt;gemSpawn+=dt;if(spawn>Math.max(48,70-score/1000)){obs.push({x:1200,y:G-55,w:55,h:55});spawn=0}if(gemSpawn>28){gems.push({x:1200,y:150+Math.random()*210});gemSpawn=0}}
function collide(a,b){return a.x+8<b.x+b.w&&a.x+a.w-8>b.x&&a.y+8<b.y+b.h&&a.y+a.h>b.y}
function update(dt){score+=dt*.22;speed=Math.min(18,7+score/1800+save.upgrades.speed*.5);if(dashTimer>0){dashTimer-=dt;speed+=8}P.vy+=.85*dt;P.y+=P.vy*dt;if(P.y>=G-P.h){P.y=G-P.h;P.vy=0;P.jumps=0}spawnStuff(dt);for(let i=obs.length-1;i>=0;i--){obs[i].x-=speed*dt;if(collide(P,obs[i])){if(shieldActive){shieldActive=false;obs.splice(i,1);combo=Math.min(10,combo+1)}else{health--;combo=1;obs.splice(i,1);if(health<=0)return end()}}else if(obs[i].x<-80)obs.splice(i,1)}for(let i=gems.length-1;i>=0;i--){gems[i].x-=speed*dt;if(Math.hypot(gems[i].x-P.x,gems[i].y-P.y)<65){save.gems+=25;save.missions.gems=Math.min(100,save.missions.gems+25);score+=50;combo=Math.min(10,combo+1);gems.splice(i,1);persist();renderMissions()}else if(gems[i].x<-50)gems.splice(i,1)}ui()}
function draw(){const grad=ctx.createLinearGradient(0,0,0,520);grad.addColorStop(0,"#080b24");grad.addColorStop(.55,"#170d30");grad.addColorStop(1,"#071d22");ctx.fillStyle=grad;ctx.fillRect(0,0,1200,520);for(let i=0;i<90;i++){ctx.fillStyle=i%5===0?"#62ecff99":"#ffffff88";ctx.fillRect((i*173-score*.05)%1200,25+(i*47)%290,2+(i%3),2+(i%2))}ctx.fillStyle="#183b52";for(let i=0;i<9;i++){const x=i*180-(score*.03%180);ctx.beginPath();ctx.moveTo(x,430);ctx.lineTo(x+80,290-(i%2)*50);ctx.lineTo(x+160,430);ctx.fill()}ctx.fillStyle="#102f34";ctx.fillRect(0,G,1200,90);ctx.strokeStyle="#65f6ff";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,G);ctx.lineTo(1200,G);ctx.stroke();gems.forEach(z=>{ctx.fillStyle="#61eaff";ctx.shadowBlur=20;ctx.shadowColor="#61eaff";ctx.beginPath();ctx.moveTo(z.x,z.y-14);ctx.lineTo(z.x+12,z.y);ctx.lineTo(z.x,z.y+14);ctx.lineTo(z.x-12,z.y);ctx.fill();ctx.shadowBlur=0});obs.forEach(o=>{ctx.fillStyle="#ff4f8d";ctx.shadowBlur=12;ctx.shadowColor="#ff4f8d";ctx.beginPath();ctx.moveTo(o.x,o.y+o.h);ctx.lineTo(o.x+27,o.y);ctx.lineTo(o.x+o.w,o.y+o.h);ctx.closePath();ctx.fill();ctx.shadowBlur=0});const skin=skins[save.skin]||skins[0];ctx.save();if(shieldActive){ctx.strokeStyle="#62ecff";ctx.lineWidth=5;ctx.shadowBlur=25;ctx.shadowColor="#62ecff";ctx.beginPath();ctx.arc(P.x+29,P.y+35,48,0,Math.PI*2);ctx.stroke()}ctx.fillStyle="#62ffab";ctx.shadowBlur=25;ctx.shadowColor="#62ffab";ctx.fillRect(P.x,P.y+20,P.w,P.h-20);ctx.beginPath();ctx.arc(P.x+48,P.y+18,23,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#101020";ctx.fillRect(P.x+54,P.y+12,5,5);ctx.fillStyle="#fff";ctx.font="bold 18px Arial";ctx.textAlign="center";ctx.fillText(skin[1],P.x+29,P.y+54);ctx.restore();if(dashTimer>0){ctx.fillStyle="#62ecff55";for(let i=1;i<5;i++)ctx.fillRect(P.x-i*25,P.y+25,14,4)}}
function loop(t){if(!running)return;const dt=Math.min(2,(t-last)/16.67);last=t;update(dt);draw();if(running)requestAnimationFrame(loop)}
document.addEventListener("keydown",e=>{if(e.code==="Space"||e.code==="ArrowUp"){e.preventDefault();jump()}if(e.code==="KeyD"){e.preventDefault();dash()}if(e.code==="KeyS"){e.preventDefault();shield()}});
$("startButton")&&($("startButton").onclick=start);$("restartButton")&&($("restartButton").onclick=start);$("jumpButton")&&($("jumpButton").onclick=jump);$("dashButton")&&($("dashButton").onclick=dash);$("shieldButton")&&($("shieldButton").onclick=shield);$("redeemButton")&&($("redeemButton").onclick=redeem);$("codeInput")&&$("codeInput").addEventListener("keydown",e=>{if(e.key==="Enter")redeem()});
tabs();renderSkins();renderMissions();renderWorlds();renderShop();ui();reset();draw();