(()=>{
'use strict';
const $=id=>document.getElementById(id);
const canvas=$('gameCanvas');
if(!canvas) return;
const ctx=canvas.getContext('2d');
if(!ctx) return;
const W=1440,H=760,G=575,LANES=[360,720,1080];
const SAVE='DINO_LEGENDS_V23';
const SKINS=[['Rookie Rex','🦖',0],['Neon Rex','🤖',2500],['Ember Rex','🔥',5000],['Frost Rex','❄️',7500],['Cyber Raptor','⚡',10000],['Jungle King','🌿',15000],['Crystal Rex','💎',22000],['Shadow Rex','🌑',30000],['Solar Rex','☀️',40000],['Galaxy Rex','🌌',60000],['Mecha Titan','🦾',90000],['Void Emperor','👑',150000]];
const WORLDS=[['Ancient Jungle',0,1],['Volcanic Wastes',5000,1.12],['Frost Realm',15000,.94],['Sky Ruins',30000,1.05],['Void Realm',60000,1.2]];
const UPGRADES=[['HEALTH','❤️','Max HP +1',800],['ENERGY CORE','⚡','Max energy +20',1200],['DASH ENGINE','💨','Dash costs 5 less',1600],['COMBO AMP','🔥','Combo score +12%',2200],['GEM MAGNET','🧲','More run gems',2800],['PARRY MATRIX','🛡️','Parry window +0.10s',3500],['RAGE CORE','☄️','Rage gains +20%',4500],['LUCK','🍀','Rare events more often',6000]];
const MISSIONS=[['Combo Master','Reach x10 combo',10],['Gem Hunter','Collect 25 gems',25],['Air Ace','Defeat 15 airborne foes',15],['Guardian Slayer','Defeat 3 guardians',3],['Distance Runner','Survive 120 seconds',120],['Elite Hunter','Defeat 20 elites',20],['Perfect Timing','Land 10 parries',10],['World Traveler','Unlock 3 worlds',3]];
const defaults={gems:2500,best:0,skin:0,owned:[0],up:{},world:0,mission:{},stats:{gems:0,air:0,boss:0,time:0,elite:0,parry:0,runs:0},used:[]};
function load(){try{const v=JSON.parse(localStorage.getItem(SAVE));if(!v)return structuredClone(defaults);return {...structuredClone(defaults),...v,owned:Array.isArray(v.owned)?[...new Set(v.owned.filter(Number.isInteger))]:[0],up:v.up&&typeof v.up==='object'?v.up:{},mission:v.mission&&typeof v.mission==='object'?v.mission:{},stats:{...defaults.stats,...(v.stats||{})},used:Array.isArray(v.used)?v.used:[]};}catch{return structuredClone(defaults)}}
let save=load();
const persist=()=>{try{localStorage.setItem(SAVE,JSON.stringify(save))}catch{}};
let run=false,paused=false,last=0,time=0,score=0,runGems=0,hp=3,maxHp=3,energy=100,maxEnergy=100,rage=0,combo=1,peak=1,world=save.world||0,spawnTimer=.5,boss=null,objects=[],particles=[],texts=[];
const P={lane:1,x:720,y:0,vy:0,jumps:0,attack:0,dash:0,parry:0,inv:0};
const has=i=>(save.up[i]||0)>0;
const maxHealth=()=>3+(save.up[0]||0);
const energyLimit=()=>100+(save.up[1]||0)*20;
const dashCost=()=>Math.max(15,35-(save.up[2]||0)*5);
const scoreMult=()=>1+(save.up[3]||0)*.12;
const gemMult=()=>1+(save.up[4]||0)*.25;
const parryTime=()=>.32+(save.up[5]||0)*.1;
const rageMult=()=>1+(save.up[6]||0)*.2;
function resize(){const r=canvas.getBoundingClientRect();const d=Math.min(devicePixelRatio||1,1.7);canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)}
addEventListener('resize',resize,{passive:true});resize();
function panel(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id))}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>panel(b.dataset.panel)));
function missionValue(i){const a=save.stats;return [peak,a.gems,a.air,a.boss,Math.floor(a.time),a.elite,a.parry,save.world+1][i]}
function render(){
 const skin=$('skins');if(skin)skin.innerHTML=`<div class="heading"><div><small>CUSTOMIZATION</small><h2>SKIN FORGE</h2></div><b>${save.gems.toLocaleString()} GEMS</b></div><div class="grid">${SKINS.map((s,i)=>{const owned=save.owned.includes(i);return `<article class="item skinCard ${save.skin===i?'selected':''}"><div class="icon skinIcon">${s[1]}</div><h3>${s[0]}</h3><small>${i===0?'STARTER':i<4?'RARE':i<8?'EPIC':i<11?'LEGENDARY':'MYTHIC'}</small><p>${i?'Visual skin with unique aura.':'Balanced starter skin.'}</p><footer><span class="price">${owned?(save.skin===i?'EQUIPPED':'OWNED'):s[2].toLocaleString()+' GEMS'}</span><button class="action skinBtn" data-i="${i}" ${!owned&&save.gems<s[2]?'disabled':''}>${owned?(save.skin===i?'EQUIPPED':'EQUIP'):'UNLOCK'}</button></footer></article>`}).join('')}</div>`;
 const ab=$('abilities');if(ab)ab.innerHTML=`<div class="heading"><div><small>PROGRESSION</small><h2>UPGRADE LAB</h2></div><b>${Object.values(save.up).reduce((a,v)=>a+Number(v||0),0)} LEVELS</b></div><div class="grid">${UPGRADES.map((u,i)=>{const lv=Math.min(5,Number(save.up[i]||0)),cost=Math.floor(u[3]*Math.pow(1.65,lv));return `<article class="item"><div class="icon">${u[1]}</div><h3>${u[0]}</h3><small>LEVEL ${lv}/5</small><p>${u[2]}</p><footer><span class="price">${lv>=5?'MAX':cost.toLocaleString()+' GEMS'}</span><button class="action upgradeBtn" data-i="${i}" ${lv>=5||save.gems<cost?'disabled':''}>${lv>=5?'MAX':'UPGRADE'}</button></footer></article>`}).join('')}</div>`;
 const mi=$('missions');if(mi)mi.innerHTML=`<div class="heading"><div><small>PROGRESSION</small><h2>MISSIONS</h2></div></div>${MISSIONS.map((m,i)=>{const v=Math.min(m[2],missionValue(i));const done=!!save.mission[i];return `<div class="mission"><span><b>${m[0]}</b><small>${m[1]} · ${v}/${m[2]}</small></span><b>${done?'CLAIMED':'+'+(i+1)*750+' GEMS'}</b></div>`}).join('')}`;
 const wo=$('worlds');if(wo)wo.innerHTML=`<div class="heading"><div><small>EXPEDITION MAP</small><h2>WORLDS</h2></div></div><div class="grid">${WORLDS.map((w,i)=>`<article class="item ${save.world>=i?'':'locked'}"><div class="icon">${['🌴','🌋','❄️','🏛️','🌌'][i]}</div><h3>${w[0]}</h3><small>${save.world>=i?'UNLOCKED':'REQUIRES '+w[1].toLocaleString()+' BEST SCORE'}</small><p>Speed ×${w[2].toFixed(2)} · new hazards.</p><footer><button class="action worldBtn" data-i="${i}" ${save.world<i?'disabled':''}>${world===i?'ACTIVE':'ENTER'}</button></footer></article>`).join('')}</div>`;
 document.querySelectorAll('.skinBtn').forEach(b=>b.onclick=()=>buySkin(+b.dataset.i));
 document.querySelectorAll('.upgradeBtn').forEach(b=>b.onclick=()=>buyUpgrade(+b.dataset.i));
 document.querySelectorAll('.worldBtn').forEach(b=>b.onclick=()=>{world=+b.dataset.i;render();hud()});
}
function buySkin(i){if(save.owned.includes(i)){save.skin=i;persist();render();return}if(save.gems<SKINS[i][2])return;save.gems-=SKINS[i][2];save.owned.push(i);save.skin=i;persist();render();hud()}
function buyUpgrade(i){const lv=Number(save.up[i]||0);if(lv>=5)return;const cost=Math.floor(UPGRADES[i][3]*Math.pow(1.65,lv));if(save.gems<cost)return;save.gems-=cost;save.up[i]=lv+1;persist();render();hud()}
function completeMissions(){MISSIONS.forEach((m,i)=>{if(!save.mission[i]&&missionValue(i)>=m[2]){save.mission[i]=1;save.gems+=(i+1)*750;pop(720,180,'MISSION COMPLETE +'+(i+1)*750,'gold')}});persist();render()}
function reset(){run=true;paused=false;time=0;score=0;runGems=0;maxHp=maxHealth();hp=maxHp;maxEnergy=energyLimit();energy=maxEnergy;rage=0;combo=1;peak=1;spawnTimer=.45;boss=null;objects.length=particles.length=texts.length=0;Object.assign(P,{lane:1,x:LANES[1],y:0,vy:0,jumps:0,attack:0,dash:0,parry:0,inv:0});save.stats.runs++;persist();$('startScreen')?.classList.add('hidden');$('gameOverScreen')?.classList.add('hidden');$('pauseScreen')?.classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function end(){if(!run)return;run=false;const final=Math.floor(score);save.best=Math.max(save.best,final);save.gems+=Math.floor(runGems*gemMult());save.stats.gems+=Math.floor(runGems);save.stats.time+=time;if(final>=WORLDS[Math.min(WORLDS.length-1,save.world+1)][1])save.world=Math.min(WORLDS.length-1,save.world+1);persist();completeMissions();$('finalScore').textContent=final.toLocaleString();$('finalStats').textContent=`WORLD ${WORLDS[world][0]} · PEAK x${peak.toFixed(1)} · +${Math.floor(runGems*gemMult())} GEMS`;$('gameOverScreen')?.classList.remove('hidden');hud()}
function action(a){if(!run||paused)return;if(a==='left')P.lane=Math.max(0,P.lane-1);else if(a==='right')P.lane=Math.min(2,P.lane+1);else if(a==='jump'&&P.jumps<2){P.vy=P.jumps?-780:-940;P.jumps++;burst(P.x,G-P.y,8,'cyan')}else if(a==='attack')P.attack=.22;else if(a==='dash'&&energy>=dashCost()){energy-=dashCost();P.dash=.38;P.inv=.5;burst(P.x,G-P.y,18,'gold')}else if(a==='parry'&&energy>=20){energy-=20;P.parry=parryTime()}else if(a==='rage'&&rage>=100){rage=0;score+=2200*combo;combo=Math.min(30,combo+3);burst(P.x,G-P.y,25,'violet')}}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();action(b.dataset.action)}));
addEventListener('keydown',e=>{if(['Space','ArrowLeft','ArrowRight','ArrowUp'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft'||e.code==='KeyA')action('left');else if(e.code==='ArrowRight'||e.code==='KeyD')action('right');else if(e.code==='Space'||e.code==='ArrowUp')action('jump');else if(e.code==='KeyF')action('attack');else if(e.code==='ShiftLeft'||e.code==='ShiftRight')action('dash');else if(e.code==='KeyS')action('parry');else if(e.code==='KeyR')action('rage');else if(e.code==='Escape'&&run){paused=!paused;$('pauseScreen')?.classList.toggle('hidden',!paused);if(!paused)last=performance.now()}else if(e.code==='Enter'&&!run)reset()});
$('startButton')?.addEventListener('click',reset);$('restartButton')?.addEventListener('click',reset);$('resumeButton')?.addEventListener('click',()=>{paused=false;$('pauseScreen')?.classList.add('hidden');last=performance.now()});
function spawn(type,lane,x=W+100){const d={rock:[70,60,G-30],spike:[68,42,G-18],enemy:[68,75,G-38],elite:[82,88,G-45],air:[72,48,390],gem:[30,30,G-120],meteor:[90,50,330],crystal:[38,50,G-160]}[type];if(d)objects.push({type,lane,x,w:d[0],y:d[2],hp:type==='elite'?2:1,cool:0,dead:false})}
function pattern(){const r=Math.random(),l=Math.floor(Math.random()*3);if(time<6){spawn(r<.65?'rock':'gem',l);return}const rare=0.1+(save.up[7]||0)*.035;if(r<rare){spawn('meteor',l);spawn('crystal',(l+1)%3,W+230)}else if(r<.28){spawn('enemy',l);spawn('air',(l+1)%3,W+250)}else if(r<.45){spawn('rock',l);spawn('spike',(l+1)%3,W+210)}else if(r<.60){spawn('elite',l)}else if(r<.75){spawn('air',l);spawn('gem',(l+2)%3,W+190)}else{spawn('spike',l);spawn('rock',(l+2)%3,W+250)}}
function damage(){if(P.inv>0)return;if(P.parry>0){score+=650*combo;combo=Math.min(30,combo+1.7);peak=Math.max(peak,combo);rage=Math.min(100,rage+8*rageMult());P.parry=0;save.stats.parry++;pop(P.x,G-100,'PERFECT PARRY','gold');return}hp--;combo=1;P.inv=1;pop(P.x,G-90,'HIT','red');if(hp<=0)end()}
function defeat(o){o.hp--;if(o.hp>0)return;o.dead=true;const elite=o.type==='elite';if(o.type==='air')save.stats.air++;if(elite)save.stats.elite++;if(o.type==='crystal')runGems+=2;runGems+=elite?4:1;score+=(elite?900:300)*combo*scoreMult();combo=Math.min(30,combo+(elite?1.1:.7));peak=Math.max(peak,combo);rage=Math.min(100,rage+6*rageMult());burst(o.x,o.y,15,'gold');pop(o.x,o.y-20,'KO','cyan')}
function collide(o){if(o.dead||o.cool>0||o.lane!==P.lane||Math.abs(o.x-P.x)>o.w*.55+34)return;o.cool=.2;if(o.type==='gem'||o.type==='crystal'){o.dead=true;runGems+=o.type==='crystal'?3:1;score+=350*combo;combo=Math.min(30,combo+.35);peak=Math.max(peak,combo);return}if(o.type==='air'){if(P.y>90||P.dash>0)defeat(o);else damage();return}if(P.attack>0||P.dash>0)defeat(o);else if(P.y>80){o.dead=true;score+=220*combo;combo=Math.min(30,combo+.5);peak=Math.max(peak,combo)}else damage()}
function startBoss(){if(boss)return;boss={x:1120,hp:20,max:20,cool:.8};pop(720,150,'WORLD GUARDIAN','gold')}
function bossUpdate(dt,speed){if(!boss)return;boss.x=Math.max(800,boss.x-speed*.25*dt);boss.cool-=dt;if(boss.cool<=0){boss.cool=.7+Math.random()*.5;const l=Math.floor(Math.random()*3);spawn('air',l,W+100);spawn('meteor',(l+1)%3,W+220)}if(Math.abs(boss.x-P.x)<125&&P.lane===1){if(P.attack>0||P.dash>0){boss.hp--;score+=900*combo;combo=Math.min(30,combo+1);if(boss.hp<=0){boss=null;runGems+=30;save.stats.boss++;pop(1000,170,'GUARDIAN DEFEATED','gold')}}else damage()}}
function update(dt){time+=dt;const speed=Math.min(980,(430+time*7+combo*3)*WORLDS[world][2]);energy=Math.min(maxEnergy,energy+dt*11);P.attack=Math.max(0,P.attack-dt);P.dash=Math.max(0,P.dash-dt);P.parry=Math.max(0,P.parry-dt);P.inv=Math.max(0,P.inv-dt);P.x+=(LANES[P.lane]-P.x)*Math.min(1,dt*15);P.vy+=2200*dt;P.y+=P.vy*dt;if(P.y<=0){P.y=0;P.vy=0;P.jumps=0}spawnTimer-=dt;if(spawnTimer<=0){pattern();spawnTimer=Math.max(.28,.86-time*.002)}if(rage>=100&&time>15&&!boss&&Math.random()<.003)startBoss();for(let i=objects.length-1;i>=0;i--){const o=objects[i];o.x-=speed*dt;o.cool=Math.max(0,o.cool-dt);if(o.x<-220){objects.splice(i,1);continue}collide(o)}bossUpdate(dt,speed);if(combo>1)combo=Math.max(1,combo-dt*.065);score+=dt*speed*.035*combo*scoreMult();if(Math.floor(time)!==Math.floor(time-dt)){save.stats.time+=1}hud()}
function burst(x,y,n,type){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*500,vy:(Math.random()-.9)*420,l:.5+Math.random()*.5,type})}
function pop(x,y,v,type){texts.push({x,y,v,type,l:1})}
function scene(){const sky=['#071b35','#321307','#dbeeff','#17103b','#03020c'][world],ground=['#09261b','#35120b','#b9d7e0','#17162f','#090712'][world];const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,sky);g.addColorStop(1,ground);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.35)';for(let i=0;i<55;i++){const sx=(i*137-time*20)%W;ctx.fillRect((sx+W)%W,40+(i*41)%260,2,2)}ctx.fillStyle=ground;ctx.fillRect(0,G,W,H)}
function dino(){const y=G-P.y;const colors=['#5cf0bd','#00eaff','#ff7b38','#9beaff','#ffe35a','#58ff9c','#d7c7ff','#a77bff','#fff08a','#8b7dff','#d7e9ff','#b58cff'];ctx.save();ctx.translate(P.x,y);if(P.inv&&Math.floor(P.inv*18)%2===0)ctx.globalAlpha=.35;ctx.fillStyle=colors[save.skin]||colors[0];ctx.shadowBlur=P.dash?35:16;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.ellipse(0,-45,34,46,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(28,-82,35,29,-.1,0,Math.PI*2);ctx.fill();ctx.fillStyle='#08141b';ctx.beginPath();ctx.arc(43,-88,5,0,Math.PI*2);ctx.fill();ctx.fillStyle=colors[save.skin]||colors[0];ctx.fillRect(-25,-8,13,40);ctx.fillRect(12,-8,13,40);if(save.skin>=4){ctx.strokeStyle=colors[save.skin];ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,-55,55,-2.4,1.2);ctx.stroke()}if(P.attack){ctx.strokeStyle='#fff';ctx.lineWidth=9;ctx.beginPath();ctx.arc(48,-55,62,-1.2,1.1);ctx.stroke()}ctx.restore()}
function drawObjects(){for(const o of objects){if(o.dead)continue;ctx.save();ctx.translate(o.x,o.y);const col=o.type==='meteor'?'#ff5a36':o.type==='crystal'?'#a77bff':o.type==='gem'?'#55eaff':o.type==='air'?'#c8f7ff':o.type==='elite'?'#ffcc55':'#6d8b80';ctx.fillStyle=col;ctx.shadowBlur=12;ctx.shadowColor=col;if(['spike','meteor'].includes(o.type)){ctx.beginPath();ctx.moveTo(-35,30);ctx.lineTo(0,-30);ctx.lineTo(35,30);ctx.closePath();ctx.fill()}else if(['gem','crystal'].includes(o.type)){ctx.rotate(Math.PI/4);ctx.fillRect(-15,-15,30,30)}else{ctx.beginPath();ctx.arc(0,0,o.w*.45,0,Math.PI*2);ctx.fill()}ctx.restore()}}
function hud(){if($('health'))$('health').textContent='●'.repeat(Math.max(0,hp))+'○'.repeat(Math.max(0,maxHp-hp));if($('energyText'))$('energyText').textContent=Math.floor(energy);if($('score'))$('score').textContent=Math.floor(score).toLocaleString();if($('combo'))$('combo').textContent='x'+combo.toFixed(1);if($('gems'))$('gems').textContent=(save.gems+Math.floor(runGems*gemMult())).toLocaleString();if($('guardianHud'))$('guardianHud').textContent=boss?'BOSS':'RUN';if($('energyBar'))$('energyBar').style.width=Math.min(100,energy/maxEnergy*100)+'%';if($('rageBar'))$('rageBar').style.width=rage+'%';if($('bossBar'))$('bossBar').style.width=boss?(boss.hp/boss.max*100)+'%':'0%';if($('bestScore'))$('bestScore').textContent=save.best.toLocaleString();if($('rank'))$('rank').textContent=save.best>=60000?'MYTHIC':save.best>=30000?'LEGEND':save.best>=15000?'ELITE':save.best>=5000?'HUNTER':'ROOKIE'}
function draw(){scene();drawObjects();for(const q of particles){q.x+=q.vx/60;q.y+=q.vy/60;q.l-=.016;ctx.globalAlpha=Math.max(0,q.l);ctx.fillStyle=q.type==='red'?'#ff5555':q.type==='violet'?'#bd7cff':q.type==='gold'?'#ffd95a':'#6eeeff';ctx.fillRect(q.x,q.y,5,5)}for(let i=particles.length-1;i>=0;i--)if(particles[i].l<=0)particles.splice(i,1);ctx.globalAlpha=1;dino();for(const q of texts){q.y-=.7;q.l-=.02;ctx.globalAlpha=Math.max(0,q.l);ctx.fillStyle='#fff';ctx.font='bold 22px Arial';ctx.textAlign='center';ctx.fillText(q.v,q.x,q.y)}for(let i=texts.length-1;i>=0;i--)if(texts[i].l<=0)texts.splice(i,1);ctx.globalAlpha=1}
function loop(now){if(!run)return;if(!paused){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw()}else last=now;requestAnimationFrame(loop)}
$('codeInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('redeemButton')?.click()});$('redeemButton')?.addEventListener('click',()=>{const input=$('codeInput'),msg=$('codeMessage'),code=(input?.value||'').trim().toUpperCase();const rewards={TRILLION1:1000000000000,DINO100:100,LEGEND500:500,FANTASY1K:1000,MYTHIC50K:50000,LEGENDARY1M:1000000};if(!code){msg.textContent='ENTER A CODE';return}if(save.used.includes(code)){msg.textContent='ALREADY REDEEMED';return}if(rewards[code]){save.gems+=rewards[code];save.used.push(code);persist();msg.textContent='REWARD ADDED: '+rewards[code].toLocaleString()+' GEMS';render();hud()}else msg.textContent='INVALID CODE'});
render();hud();
})();
