(()=>{
'use strict';
const $=id=>document.getElementById(id),canvas=$('gameCanvas');if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;
const W=1440,H=760,G=610,LANES=[350,720,1090],SAVE='DINO_LEGENDS_V30';
const SKINS=[
['Verdant Rex','#5ee6a8','NATURE','RARE'],['Ember Fang','#ff7043','FIRE','RARE'],['Frost Claw','#7ddfff','ICE','RARE'],['Volt Raptor','#ffe26b','STORM','EPIC'],['Void Stalker','#a889ff','VOID','EPIC'],['Solar Tyrant','#ffd86b','SOLAR','EPIC'],['Crystal Drake','#ff8fe8','CRYSTAL','EPIC'],['Toxic Hunter','#a8ff68','TOXIC','LEGENDARY'],['Cyber Rex','#3ee8ff','CYBER','LEGENDARY'],['Shadow Warden','#d19cff','SHADOW','LEGENDARY'],['Ocean Leviathan','#58aaff','OCEAN','LEGENDARY'],['Lava Colossus','#ff634f','MAGMA','LEGENDARY'],['Thunder King','#b7c4ff','THUNDER','MYTHIC'],['Moon Beast','#c9baff','MOON','MYTHIC'],['Star Eater','#ffe98a','COSMIC','MYTHIC'],['Bloodmoon Rex','#ff708a','BLOOD','MYTHIC'],['Ancient Guardian','#d8ad7b','ANCIENT','DIVINE'],['Neon Phantom','#5fffe2','NEON','DIVINE'],['Chrono Dragon','#9fb8ff','CHRONO','DIVINE'],['Galaxy Emperor','#d09aff','GALAXY','DIVINE'],['Omega Titan','#ffffff','OMEGA','DIVINE'],['Prism Overlord','#ff9fdf','PRISM','DIVINE'],['Inferno Prime','#ffb45b','PRIME','DIVINE'],['Dino Legend','#ffe77a','LEGEND','DIVINE'],['Obsidian King','#b8c0ce','OBSIDIAN','ASCENDANT'],['Aurora Reaper','#8fffe0','AURORA','ASCENDANT'],['Solaris Apex','#fff1a6','APEX','ASCENDANT'],['Rift Monarch','#c28cff','RIFT','ASCENDANT'],['Titanium Prime','#dce7ff','TITANIUM','ASCENDANT'],['Eclipse Sovereign','#8d9bff','ECLIPSE','ASCENDANT']
];
const WORLDS=[['Emerald Wilds','JUNGLE',0,1.00,'humid'],['Ashfall Caldera','VOLCANO',9000,1.10,'ash'],['Frostline Basin','ICE',22000,.96,'snow'],['Sky Citadel','SKY',42000,1.06,'storm'],['Neon Abyss','NEON',70000,1.15,'rain'],['Cosmic Rift','COSMIC',110000,1.24,'stars'],['Titan Graveyard','TITAN',170000,1.30,'dust'],['Eclipse Frontier','ECLIPSE',250000,1.38,'eclipse']];
const UP=[['Vital Core','+1 maximum HP',700],['Energy Reactor','+20 maximum energy',1000],['Dash Drive','-5 dash energy',1300],['Combo Engine','+10% combo score',1800],['Gem Magnet','+25% gem value',2200],['Parry Matrix','+0.10s parry window',2700],['Rage Reactor','+20% rage gain',3200],['Lucky Core','more rare events',3900],['Hunter Protocol','+8% enemy score',4600],['Guardian Core','+12% boss damage',5500],['Momentum Drive','+12% movement score',6500],['Phoenix Protocol','one emergency revive',7800]];
const MISS=[['Combo Architect','Reach x15 combo',15],['Gem Rush','Collect 60 gems',60],['Air Hunter','Defeat 30 airborne enemies',30],['Elite Breaker','Defeat 30 elites',30],['Perfect Guard','Land 15 perfect parries',15],['Guardian Hunter','Defeat 5 guardians',5],['Long Haul','Survive 180 seconds',180],['Explorer','Unlock 5 worlds',5],['Untouchable','Finish a run without damage',1],['Speed Demon','Reach 9000 score in 45s',1],['Relic Hunter','Collect 12 relics',12],['Apex','Reach x25 combo',25]];
const D={gems:2500,best:0,skin:0,owned:[0],up:{},world:0,missions:{},stats:{gems:0,air:0,elite:0,parry:0,boss:0,time:0,relic:0,clean:0,speed:0}};
const clone=o=>JSON.parse(JSON.stringify(o));let save=(()=>{try{const v=JSON.parse(localStorage.getItem(SAVE));return {...clone(D),...v,owned:Array.isArray(v.owned)?[...new Set(v.owned)]:[0],up:v.up||{},missions:v.missions||{},stats:{...D.stats,...(v.stats||{})}}}catch{return clone(D)}})();
const persist=()=>localStorage.setItem(SAVE,JSON.stringify(save));const up=i=>Number(save.up[i]||0);const gemMult=()=>1+up(4)*.25;const scoreMult=()=>1+up(3)*.1+up(8)*.08+up(10)*.12;const dashCost=()=>Math.max(10,34-up(2)*5);const parryWindow=()=>.28+up(5)*.1;const rageMult=()=>1+up(6)*.2;
let running=false,paused=false,last=0,time=0,score=0,runGems=0,hp=3,maxHp=3,energy=100,maxEnergy=100,rage=0,combo=1,peak=1,world=save.world||0,spawn=.45,boss=null,objects=[],particles=[],texts=[],shake=0,flash=0,weather=[],relics=0,reviveUsed=false;
const P={lane:1,x:720,y:0,vy:0,jumps:0,attack:0,dash:0,parry:0,inv:0,tilt:0};
for(let i=0;i<120;i++)weather.push({x:Math.random()*W,y:Math.random()*H,r:.4+Math.random()*2,s:40+Math.random()*100,a:.15+Math.random()*.5});
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)}addEventListener('resize',resize,{passive:true});resize();
function panel(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id))}document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>panel(b.dataset.panel));
function esc(s){return String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function render(){
 const s=$('skins');if(s)s.innerHTML=`<div class="heading"><div><small>LEGEND VAULT · ${save.owned.length}/${SKINS.length} COLLECTED</small><h2>SKIN FORGE</h2></div><b>${save.gems.toLocaleString()} GEMS</b></div><div class="grid skinGrid">${SKINS.map((v,i)=>{const owned=save.owned.includes(i),active=save.skin===i,price=i?Math.floor(1000*Math.pow(1.28,i)):0;return `<article class="item skinCard ${active?'selected':''}" style="--glow:${v[1]}"><div class="skinPreview"><div class="dinoModel"><span></span><i></i></div><b>${String(i+1).padStart(2,'0')}</b></div><div class="skinTags"><span>${v[3]}</span><span>${v[2]}</span></div><h3>${esc(v[0])}</h3><small>ARMOR · CORE · TRAIL · FINISHER</small><div class="skinStats"><i>DMG ${100+i*2}</i><i>ARM ${100+i}</i><i>SPD ${100+(i%9)*3}</i></div><footer><span class="price">${owned?(active?'EQUIPPED':'OWNED'):price.toLocaleString()+' GEMS'}</span><button class="action skinBtn" data-i="${i}" ${!owned&&save.gems<price?'disabled':''}>${owned?(active?'EQUIPPED':'EQUIP'):'UNLOCK'}</button></footer></article>`}).join('')}</div>`;
 const a=$('abilities');if(a)a.innerHTML=`<div class="heading"><div><small>12 SYSTEMS · 5 LEVELS EACH</small><h2>UPGRADE LAB</h2></div><b>${Object.values(save.up).reduce((x,y)=>x+Number(y||0),0)} LEVELS</b></div><div class="grid">${UP.map((u,i)=>{let lv=Math.min(5,up(i)),cost=Math.floor(u[2]*Math.pow(1.55,lv));return `<article class="item upgradeCard"><div class="icon">${['CORE','REACTOR','DRIVE','COMBO','MAGNET','MATRIX','RAGE','LUCK','HUNTER','GUARDIAN','MOMENTUM','PHOENIX'][i]}</div><h3>${u[0]}</h3><small>LEVEL ${lv}/5</small><p>${u[1]}</p><div class="levelDots">${[0,1,2,3,4].map(n=>`<i class="${n<lv?'on':''}"></i>`).join('')}</div><footer><span class="price">${lv>=5?'MAX':cost.toLocaleString()+' GEMS'}</span><button class="action upBtn" data-i="${i}" ${lv>=5||save.gems<cost?'disabled':''}>${lv>=5?'MAX':'UPGRADE'}</button></footer></article>`}).join('')}</div>`;
 const m=$('missions');if(m)m.innerHTML=`<div class="heading"><div><small>OPERATIONS · ${Object.keys(save.missions).length}/${MISS.length}</small><h2>MISSIONS</h2></div></div>${MISS.map((q,i)=>{const v=missionValue(i),done=!!save.missions[i],reward=(i+1)*1000;return `<div class="mission"><span><b>${q[0]}</b><small>${q[1]} · ${Math.min(q[2],v)}/${q[2]}</small></span><button class="action missBtn" data-i="${i}" ${done||v<q[2]?'disabled':''}>${done?'CLAIMED':'CLAIM '+reward}</button></div>`}).join('')}`;
 const w=$('worlds');if(w)w.innerHTML=`<div class="heading"><div><small>EXPEDITION NETWORK · ${world+1}/${WORLDS.length}</small><h2>WORLDS</h2></div></div><div class="grid">${WORLDS.map((q,i)=>`<article class="item worldCard ${save.world<i?'locked':''}" data-biome="${q[1]}"><div class="worldIcon">${String(i+1).padStart(2,'0')}</div><h3>${q[0]}</h3><small>${save.world>=i?'UNLOCKED':'REQUIRES '+q[2].toLocaleString()}</small><p>THREAT ×${q[3].toFixed(2)} · ${q[4].toUpperCase()} · DYNAMIC EVENTS.</p><footer><button class="action worldBtn" data-i="${i}" ${save.world<i?'disabled':''}>${world===i?'ACTIVE':'ENTER'}</button></footer></article>`).join('')}</div>`;
 document.querySelectorAll('.skinBtn').forEach(b=>b.onclick=()=>buySkin(+b.dataset.i));document.querySelectorAll('.upBtn').forEach(b=>b.onclick=()=>buyUp(+b.dataset.i));document.querySelectorAll('.worldBtn').forEach(b=>b.onclick=()=>{world=+b.dataset.i;render();hud()});document.querySelectorAll('.missBtn').forEach(b=>b.onclick=()=>claim(+b.dataset.i));
}
function buySkin(i){const price=i?Math.floor(1000*Math.pow(1.28,i)):0;if(save.owned.includes(i))save.skin=i;else if(save.gems>=price){save.gems-=price;save.owned.push(i);save.skin=i}else return;persist();render();hud()}
function buyUp(i){const lv=up(i);if(lv>=5)return;const cost=Math.floor(UP[i][2]*Math.pow(1.55,lv));if(save.gems<cost)return;save.gems-=cost;save.up[i]=lv+1;persist();render();hud()}
function missionValue(i){const st=save.stats;return [peak,st.gems,st.air,st.elite,st.parry,st.boss,Math.floor(st.time),save.world+1,st.clean,st.speed,st.relic,peak][i]}
function claim(i){if(save.missions[i]||missionValue(i)<MISS[i][2])return;save.missions[i]=1;save.gems+=(i+1)*1000;persist();render();hud()}
function start(){running=true;paused=false;time=0;score=0;runGems=0;maxHp=3+up(0);hp=maxHp;maxEnergy=100+up(1)*20;energy=maxEnergy;rage=0;combo=1;peak=1;spawn=.45;boss=null;objects=[];particles=[];texts=[];shake=0;flash=0;relics=0;reviveUsed=false;Object.assign(P,{lane:1,x:720,y:0,vy:0,jumps:0,attack:0,dash:0,parry:0,inv:0,tilt:0});save.stats.runs=(save.stats.runs||0)+1;persist();$('startScreen')?.classList.add('hidden');$('gameOverScreen')?.classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function finish(){if(!running)return;running=false;const final=Math.floor(score),reward=Math.floor(runGems*gemMult());save.best=Math.max(save.best,final);save.gems+=reward;save.stats.gems+=runGems;save.stats.time+=time;save.stats.relic+=relics;if(hp===maxHp)save.stats.clean=1;if(time<=45&&final>=9000)save.stats.speed=1;while(save.world<WORLDS.length-1&&save.best>=WORLDS[save.world+1][2])save.world++;persist();render();$('finalScore').textContent=final.toLocaleString();$('finalStats').textContent=`${WORLDS[world][0]} · PEAK x${peak.toFixed(1)} · +${reward.toLocaleString()} GEMS · ${relics} RELICS`;$('gameOverScreen')?.classList.remove('hidden');hud()}
function damage(){if(P.inv>0||P.parry>0)return;if(up(11)>0&&!reviveUsed){reviveUsed=true;P.inv=2;hp=Math.max(1,Math.ceil(maxHp*.35));flash=.6;toast('PHOENIX PROTOCOL');return}hp--;combo=Math.max(1,combo*.55);flash=.45;shake=18;toast('ARMOR HIT');if(hp<=0)finish()}
function act(a){if(!running||paused)return;if(a==='left')P.lane=Math.max(0,P.lane-1);if(a==='right')P.lane=Math.min(2,P.lane+1);if(a==='jump'&&P.jumps<2){P.vy=P.jumps?-790:-960;P.jumps++;burst(P.x,G-P.y,12,'cyan')}if(a==='attack')P.attack=.24;if(a==='dash'&&energy>=dashCost()){energy-=dashCost();P.dash=.34;P.inv=.48;burst(P.x,G-P.y,28,'gold')}if(a==='parry'&&energy>=20){energy-=20;P.parry=parryWindow()}if(a==='rage'&&rage>=100){rage=0;score+=2400*combo;combo=Math.min(35,combo+3);burst(P.x,G-P.y,45,'violet');toast('RAGE SURGE')}}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();act(b.dataset.action)}));addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft'||e.code==='KeyA')act('left');else if(e.code==='ArrowRight'||e.code==='KeyD')act('right');else if(e.code==='Space'||e.code==='ArrowUp')act('jump');else if(e.code==='KeyF')act('attack');else if(e.code==='ShiftLeft'||e.code==='ShiftRight')act('dash');else if(e.code==='KeyS')act('parry');else if(e.code==='KeyR')act('rage');else if(e.code==='Escape'&&running){paused=!paused;$('pauseScreen')?.classList.toggle('hidden',!paused);last=performance.now()}else if(e.code==='Enter'&&!running)start()});$('startButton')?.addEventListener('click',start);$('restartButton')?.addEventListener('click',start);$('resumeButton')?.addEventListener('click',()=>{paused=false;$('pauseScreen')?.classList.add('hidden');last=performance.now()});
function spawnObj(type,lane,x=W+100){const spec={rock:[78,70,G-32],spike:[80,48,G-12],enemy:[88,92,G-50],elite:[104,108,G-58],air:[92,58,390],gem:[34,34,G-135],meteor:[100,62,300],relic:[50,70,G-170],drone:[82,55,305],mine:[62,44,G-18]}[type];if(!spec)return;objects.push({type,lane,x,w:spec[0],h:spec[1],y:spec[2],hp:type==='elite'?2:1,phase:Math.random()*6,hit:false})}
function spawnDirector(){const diff=1+time*.012,types=['rock','spike','enemy','gem','air','drone','mine'];let lane=Math.floor(Math.random()*3);if(Math.random()<.18+Math.min(.25,time/120))spawnObj(types[Math.floor(Math.random()*types.length)],lane);if(Math.random()<.12*diff)spawnObj('enemy',(lane+1)%3);if(Math.random()<.055)spawnObj('relic',Math.floor(Math.random()*3));if(Math.random()<.045&&time>18)spawnObj('elite',Math.floor(Math.random()*3));if(Math.random()<.025&&time>28)spawnObj('meteor',Math.floor(Math.random()*3));if(!boss&&time>45&&Math.floor(time/45)>Math.floor((time-.016)/45))startBoss()}
function startBoss(){boss={hp:100,max:100,t:0,kind:['RAVAGER','WYRM','TITAN','VOID REAPER'][Math.floor(Math.random()*4)]};toast('GUARDIAN INCOMING');shake=12}
function burst(x,y,n,c){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*420,vy:(Math.random()-.8)*360,l:.4+Math.random()*.5,c})}
function toast(t){texts.push({t,x:720,y:180,l:1.4})}
function update(dt){time+=dt;const speed=(380+time*5)*WORLDS[world][3];P.y+=P.vy*dt;P.vy+=2350*dt;if(P.y<=0){P.y=0;P.vy=0;P.jumps=0}P.x+=(LANES[P.lane]-P.x)*Math.min(1,dt*14);P.attack=Math.max(0,P.attack-dt);P.dash=Math.max(0,P.dash-dt);P.parry=Math.max(0,P.parry-dt);P.inv=Math.max(0,P.inv-dt);energy=Math.min(maxEnergy,energy+18*dt);rage=Math.min(100,rage+10*dt*rageMult());combo=Math.max(1,combo-dt*.17);peak=Math.max(peak,combo);spawn-=dt;if(spawn<=0){spawnDirector();spawn=Math.max(.18,.58-time*.0025)/WORLDS[world][3]}
 for(let i=objects.length-1;i>=0;i--){const o=objects[i];o.x-=speed*dt;o.phase+=dt*4;const oy=o.y+Math.sin(o.phase)*8;const close=Math.abs(o.x-P.x)<(o.w+52)/2&&o.lane===P.lane&&Math.abs(oy-(G-P.y-o.h*.45))<90;
  if(close&&!o.hit){if(o.type==='gem'){runGems++;score+=120*scoreMult()*combo;combo=Math.min(35,combo+.45);o.hit=true;burst(o.x,oy,10,'gold')}else if(o.type==='relic'){relics++;score+=500*scoreMult()*combo;combo=Math.min(35,combo+1);o.hit=true;burst(o.x,oy,22,'violet')}else if(P.attack>0&&['enemy','elite','drone','mine'].includes(o.type)){o.hp--;o.hit=true;score+=(o.type==='elite'?700:260)*scoreMult()*combo;combo=Math.min(35,combo+(o.type==='elite'?1.4:.6));rage=Math.min(100,rage+12);if(o.type==='elite'&&o.hp<=0)save.stats.elite++;if(o.type==='drone')save.stats.air++;burst(o.x,oy,18,'red')}else if(P.parry>0){o.hit=true;score+=650*scoreMult()*combo;combo=Math.min(35,combo+1.2);save.stats.parry++;rage=Math.min(100,rage+22);burst(o.x,oy,28,'cyan');toast('PERFECT PARRY')}else damage()}
  if(o.hp<=0||o.hit&&o.type!=='gem'&&o.type!=='relic'&&Math.abs(o.x-P.x)<40)objects.splice(i,1);else if(o.x<-150)objects.splice(i,1)}
 if(boss){boss.t+=dt;boss.hp-=P.attack>0?42*dt*(1+up(9)*.12):0;if(Math.random()<dt*.75){const lane=Math.floor(Math.random()*3);spawnObj(boss.t%2<1?'meteor':'drone',lane,W-10)}if(boss.hp<=0){score+=6500*scoreMult()*combo;runGems+=25;save.stats.boss++;boss=null;combo=Math.min(35,combo+4);toast('GUARDIAN DOWN');burst(720,260,80,'violet')}}
 for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=600*dt;p.l-=dt;if(p.l<=0)particles.splice(i,1)}for(const t of texts)t.l-=dt;texts=texts.filter(t=>t.l>0);flash=Math.max(0,flash-dt);shake=Math.max(0,shake-dt*30);draw();hud();requestAnimationFrame(loop)}
function drawDino(){const x=P.x,y=G-P.y-72,s=1+(P.dash>0?.08:0);ctx.save();ctx.translate(x,y);ctx.rotate((P.lane-1)*.025+P.tilt);ctx.scale(s,s);const c=SKINS[save.skin]||SKINS[0],gl=c[1];ctx.shadowColor=gl;ctx.shadowBlur=28;ctx.fillStyle='#111821';ctx.strokeStyle=gl;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-58,34);ctx.lineTo(-80,2);ctx.lineTo(-58,-18);ctx.lineTo(-28,-12);ctx.lineTo(-10,-50);ctx.lineTo(24,-66);ctx.lineTo(58,-48);ctx.lineTo(74,-18);ctx.lineTo(48,-3);ctx.lineTo(72,23);ctx.lineTo(45,18);ctx.lineTo(27,42);ctx.lineTo(-5,40);ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=gl;ctx.beginPath();ctx.arc(36,-43,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#05070b';ctx.beginPath();ctx.arc(37,-44,2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(55,-22);ctx.lineTo(66,-18);ctx.stroke();ctx.fillStyle=gl;ctx.beginPath();ctx.moveTo(-48,8);ctx.lineTo(-108,32);ctx.lineTo(-53,23);ctx.fill();ctx.restore()}
function drawWorld(){const w=WORLDS[world],t=time;const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#05070d');sky.addColorStop(.52,world===5||world===7?'#171027':'#10161d');sky.addColorStop(1,'#06080b');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);
 for(let i=0;i<40;i++){const x=(i*211-t*12)%W,y=80+(i*37)%280;ctx.globalAlpha=.15+((i*17)%40)/120;ctx.fillStyle=world===2?'#d8f4ff':'#cbd4e0';ctx.beginPath();ctx.arc((x+W)%W,y,1+(i%3),0,7);ctx.fill()}ctx.globalAlpha=1;
 ctx.fillStyle='#0b1117';ctx.beginPath();ctx.moveTo(0,440);for(let x=0;x<=W;x+=80)ctx.lineTo(x,380+Math.sin(x*.008+t*.05)*65);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();
 ctx.fillStyle=world===0?'#14271d':world===1?'#2a1712':world===2?'#182b36':world===3?'#1c1b35':world===4?'#071b21':world===5?'#160f2d':world===6?'#27201c':'#17152b';ctx.beginPath();ctx.moveTo(0,G-55);for(let x=0;x<=W;x+=45)ctx.lineTo(x,G-55-Math.sin(x*.018+t*.8)*20-(x%140));ctx.lineTo(W,G);ctx.lineTo(0,G);ctx.fill();
 ctx.fillStyle='#11161c';ctx.fillRect(0,G,W,H-G);ctx.strokeStyle='#29333c';ctx.lineWidth=2;for(const lane of LANES){ctx.beginPath();ctx.moveTo(lane-150,G);ctx.lineTo(lane-80,420);ctx.stroke();ctx.beginPath();ctx.moveTo(lane+150,G);ctx.lineTo(lane+80,420);ctx.stroke()}ctx.globalAlpha=.2;for(let i=0;i<8;i++){ctx.fillStyle=world===2?'#d9f5ff':'#8b9bad';ctx.fillRect((i*220-t*speedScale())%W,G-8,90,3)}ctx.globalAlpha=1}
function speedScale(){return 1+time*.004}
function drawObject(o){const x=o.x,y=o.y+Math.sin(o.phase)*8;ctx.save();ctx.translate(x,y);ctx.shadowBlur=18;ctx.lineWidth=3;let c='#9ca8b5';if(o.type==='gem'||o.type==='relic')c=o.type==='gem'?'#ffe071':'#c48cff';if(o.type==='enemy'||o.type==='drone')c='#ff647a';if(o.type==='elite')c='#ffb45b';if(o.type==='meteor')c='#ff784d';if(o.type==='mine')c='#ff425f';ctx.shadowColor=c;ctx.fillStyle='#141b22';ctx.strokeStyle=c;if(o.type==='gem'||o.type==='relic'){ctx.rotate(Math.PI/4);ctx.fillRect(-14,-14,28,28);ctx.strokeRect(-14,-14,28,28)}else if(o.type==='enemy'||o.type==='elite'){ctx.beginPath();ctx.moveTo(-o.w/2,o.h/2);ctx.lineTo(-o.w*.3,-o.h/2);ctx.lineTo(o.w*.2,-o.h/2+15);ctx.lineTo(o.w/2,o.h/2);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=c;ctx.fillRect(8,-28,7,7)}else{ctx.beginPath();ctx.moveTo(-o.w/2,o.h/2);ctx.lineTo(0,-o.h/2);ctx.lineTo(o.w/2,o.h/2);ctx.closePath();ctx.fill();ctx.stroke()}ctx.restore()}
function draw(){ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawWorld();for(const o of objects)drawObject(o);drawDino();for(const p of particles){ctx.globalAlpha=Math.max(0,p.l*2);ctx.fillStyle=p.c==='gold'?'#ffe071':p.c==='violet'?'#c48cff':p.c==='red'?'#ff647a':'#62efff';ctx.fillRect(p.x,p.y,4,4)}ctx.globalAlpha=1;if(boss){ctx.fillStyle='#05070bcc';ctx.fillRect(390,38,660,74);ctx.strokeStyle='#ff647a';ctx.strokeRect(390,38,660,74);ctx.fillStyle='#fff';ctx.font='900 18px Orbitron';ctx.textAlign='center';ctx.fillText('GUARDIAN · '+boss.kind,720,64);ctx.fillStyle='#29151a';ctx.fillRect(470,78,500,10);ctx.fillStyle='#ff647a';ctx.fillRect(470,78,500*(boss.hp/boss.max),10)}for(const t of texts){ctx.globalAlpha=Math.min(1,t.l);ctx.fillStyle='#fff';ctx.font='900 24px Orbitron';ctx.textAlign='center';ctx.fillText(t.t,t.x,t.y);ctx.globalAlpha=1}if(flash){ctx.fillStyle=`rgba(255,70,100,${flash*.22})`;ctx.fillRect(0,0,W,H)}ctx.restore()}
function hud(){if($('health'))$('health').textContent='●'.repeat(Math.max(0,hp))+'○'.repeat(Math.max(0,maxHp-hp));if($('energyText'))$('energyText').textContent=Math.floor(energy);if($('combo'))$('combo').textContent='x'+combo.toFixed(1);if($('score'))$('score').textContent=Math.floor(score).toLocaleString();if($('gems'))$('gems').textContent=save.gems.toLocaleString();if($('bestScore'))$('bestScore').textContent=save.best.toLocaleString();if($('rank'))$('rank').textContent=save.best>250000?'ASCENDANT':save.best>110000?'MYTHIC':save.best>42000?'LEGEND':save.best>9000?'ELITE':'ROOKIE';if($('energyBar'))$('energyBar').style.width=(energy/maxEnergy*100)+'%';if($('rageBar'))$('rageBar').style.width=rage+'%';if($('bossBar'))$('bossBar').style.width=(boss?boss.hp:0)+'%';if($('guardianHud'))$('guardianHud').textContent=boss?boss.kind:'RUN'}
function loop(now){if(!running)return;if(paused){last=now;requestAnimationFrame(loop);return}const dt=Math.min(.033,(now-last)/1000||.016);last=now;update(dt)}
render();hud();draw();
})();