(() => {
'use strict';
const c=document.getElementById('gameCanvas'),x=c.getContext('2d',{alpha:false}),$=id=>document.getElementById(id);
const W=1200,H=560,G=435,L=[300,600,900];
let quality=localStorage.getItem('DL_QUALITY')||'HIGH', reduced=localStorage.getItem('DL_REDUCED')==='1', shakeOn=localStorage.getItem('DL_SHAKE')!=='0';
let dpr=1,running=false,paused=false,last=0,time=0,score=0,gems=0,health=3,energy=100,rage=0,combo=1,comboTimer=0,bossMeter=0,kills=0,perfects=0,spawnTimer=.6,shake=0,boss=null;
const p={lane:1,x:600,y:0,vy:0,jumps:0,attack:0,dash:0,parry:0,inv:0};const os=[],ps=[],texts=[];
function resize(){const r=c.getBoundingClientRect(),cap=quality==='LOW'?1:quality==='MEDIUM'?1.25:quality==='HIGH'?1.6:2;dpr=Math.min(devicePixelRatio||1,cap);c.width=Math.max(1,r.width*dpr);c.height=Math.max(1,r.height*dpr);x.setTransform(c.width/W,0,0,c.height/H,0,0)}addEventListener('resize',resize);resize();
function panel(id){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id))}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>panel(b.dataset.panel));
function reset(){running=true;paused=false;time=score=gems=0;health=3;energy=100;rage=0;combo=1;comboTimer=0;bossMeter=0;kills=perfects=0;spawnTimer=.55;boss=null;shake=0;os.length=ps.length=texts.length=0;Object.assign(p,{lane:1,x:600,y:0,vy:0,jumps:0,attack:0,dash:0,parry:0,inv:0});$('startScreen').classList.add('hidden');$('gameOverScreen').classList.add('hidden');$('pauseScreen').classList.add('hidden');last=performance.now();hud()}
function over(){if(!running)return;running=false;paused=false;const best=Math.max(+localStorage.getItem('DL_BEST')||0,score|0);localStorage.setItem('DL_BEST',best);$('finalScore').textContent=(score|0).toLocaleString();$('finalStats').textContent=`${kills} KILLS · ${perfects} PERFECT · ${gems} GEMS`;$('gameOverScreen').classList.remove('hidden');hud()}
function pause(v){if(!running)return;paused=typeof v==='boolean'?v:!paused;$('pauseScreen').classList.toggle('hidden',!paused);if(!paused)last=performance.now()}
$('startButton').onclick=reset;$('restartButton').onclick=reset;$('pauseBtn').onclick=()=>pause();$('resumeButton').onclick=()=>pause(false);
function act(a){if(!running||paused)return;if(a==='left')p.lane=Math.max(0,p.lane-1);if(a==='right')p.lane=Math.min(2,p.lane+1);if(a==='jump'&&p.jumps<2){p.vy=p.jumps?-720:-850;p.jumps++;burst(p.x,G,6,'dust')}if(a==='attack')p.attack=.24;if(a==='dash'&&energy>=35){energy-=35;p.dash=.34;p.inv=.42;burst(p.x,G-p.y,14,'gold');impact(6)}if(a==='parry'&&energy>=20){energy-=20;p.parry=.3}if(a==='rage'&&rage>=100){rage=0;score+=3000*combo;combo=Math.min(25,combo+4);burst(p.x,G-50,30,'violet');text(p.x,G-90,'RAGE BURST','gold');impact(10)}}
document.querySelectorAll('[data-action]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();act(b.dataset.action)});addEventListener('keydown',e=>{if(['Space','ArrowLeft','ArrowRight','ArrowUp'].includes(e.code))e.preventDefault();if(e.code==='ArrowLeft'||e.code==='KeyA')act('left');else if(e.code==='ArrowRight'||e.code==='KeyD')act('right');else if(e.code==='Space'||e.code==='ArrowUp')act('jump');else if(e.code==='KeyF')act('attack');else if(e.code.startsWith('Shift'))act('dash');else if(e.code==='KeyS')act('parry');else if(e.code==='KeyR')act('rage');else if(e.code==='Escape')pause();else if(e.code==='Enter'&&!running)reset()});
$('quality').value=quality;$('reducedEffects').checked=reduced;$('screenShake').checked=shakeOn;$('quality').onchange=e=>{quality=e.target.value;localStorage.setItem('DL_QUALITY',quality);resize()};$('reducedEffects').onchange=e=>{reduced=e.target.checked;localStorage.setItem('DL_REDUCED',reduced?'1':'0')};$('screenShake').onchange=e=>{shakeOn=e.target.checked;localStorage.setItem('DL_SHAKE',shakeOn?'1':'0')};$('touchToggle').onchange=e=>document.querySelector('.touch').style.display=e.target.checked?'flex':'none';
function spawn(t,l=Math.floor(Math.random()*3),xx=W+100){const s={rock:[56,52,G-30],enemy:[60,68,G-35],elite:[72,78,G-40],air:[68,40,300],gem:[25,25,G-90],trap:[64,45,G-28]}[t];if(!s)return;os.push({type:t,lane:l,x:xx,y:s[2],w:s[0],h:s[1],hp:t==='elite'?2:1,dead:false,cool:0})}
function pattern(){const l=Math.floor(Math.random()*3),r=Math.random();if(r<.16){spawn('gem',l);spawn('rock',(l+1)%3,W+210)}else if(r<.35){spawn('enemy',l);spawn('air',(l+1)%3,W+240)}else if(r<.55){spawn('rock',l);spawn('rock',(l+1)%3,W+190)}else if(r<.72&&time>10)spawn('elite',l);else spawn('trap',l)}
function burst(a,b,n,k){n=reduced?Math.min(6,n):n;for(let i=0;i<n;i++)ps.push({x:a,y:b,vx:(Math.random()-.5)*400,vy:(Math.random()-.8)*330,life:.3+Math.random()*.5,size:2+Math.random()*4,k})}function text(a,b,v,k){texts.push({x:a,y:b,v,k,life:1})}function impact(n){if(shakeOn&&!reduced)shake=Math.max(shake,n)}function addCombo(n){combo=Math.min(25,combo+n);comboTimer=3;rage=Math.min(100,rage+n*5)}
function hit(){if(p.inv>0)return;if(p.parry>0){perfects++;score+=500*combo;addCombo(1.5);rage=Math.min(100,rage+25);burst(p.x,G-40,20,'violet');text(p.x,G-80,'PERFECT PARRY','gold');p.parry=0;impact(8);return}health--;combo=1;comboTimer=0;p.inv=1;burst(p.x,G-40,16,'red');text(p.x,G-70,'HIT','red');impact(9);if(health<=0)over()}
function kill(o){o.hp--;burst(o.x,o.y,7,'gold');if(o.hp>0)return;o.dead=true;const e=o.type==='elite';kills+=e?2:1;gems+=e?3:1;score+=(e?650:190)*combo;addCombo(e?1:.65);rage=Math.min(100,rage+(e?15:8));bossMeter=Math.min(100,bossMeter+(e?12:6));burst(o.x,o.y,18,'gold');text(o.x,o.y-25,'KO','cyan');impact(5)}
function collide(o){if(o.dead||o.cool>0||o.lane!==p.lane||Math.abs(o.x-p.x)>o.w*.55+38)return;o.cool=.2;if(o.type==='gem'){o.dead=true;gems++;score+=300*combo;addCombo(.3);burst(o.x,o.y,10,'cyan');return}if(o.type==='air'){if(p.y>70||p.dash>0){o.dead=true;perfects++;score+=220*combo;addCombo(.7);rage=Math.min(100,rage+7);burst(o.x,o.y,10,'cyan');text(o.x,o.y-20,'PERFECT','gold')}else hit();return}if(p.attack>0||p.dash>0)kill(o);else if(p.y>70){o.dead=true;perfects++;score+=160*combo;addCombo(.5);rage=Math.min(100,rage+6);burst(o.x,o.y,9,'cyan');text(o.x,o.y-25,'PERFECT DODGE','gold')}else hit()}
function bossStart(){if(boss)return;boss={x:W+120,lane:1,hp:10,max:10,cool:1};text(W/2,110,'JUNGLE GUARDIAN','boss');impact(9)}
function updateBoss(dt,speed){if(!boss)return;boss.x=Math.max(930,boss.x-speed*.3*dt);boss.cool-=dt;if(boss.cool<=0){boss.cool=1.2;spawn('air',Math.floor(Math.random()*3),W+80);if(Math.random()<.55)spawn('rock',Math.floor(Math.random()*3),W+170)}if(Math.abs(boss.x-p.x)<105&&boss.lane===p.lane){if(p.attack>0||p.dash>0){boss.hp--;score+=650*combo;addCombo(1);burst(boss.x,G-90,14,'violet');impact(7);if(boss.hp<=0){score+=5000*combo;gems+=15;boss=null;bossMeter=0;burst(950,G-100,40,'gold');text(900,150,'GUARDIAN DEFEATED','gold')}}else hit()}}
function update(dt){time+=dt;const speed=Math.min(980,390+time*8+combo*3);energy=Math.min(100,energy+dt*9);p.attack=Math.max(0,p.attack-dt);p.dash=Math.max(0,p.dash-dt);p.parry=Math.max(0,p.parry-dt);p.inv=Math.max(0,p.inv-dt);p.x+=(L[p.lane]-p.x)*Math.min(1,dt*15);p.vy+=1900*dt;p.y+=p.vy*dt;if(p.y<=0){p.y=0;p.vy=0;p.jumps=0}comboTimer-=dt;if(comboTimer<=0)combo=1;spawnTimer-=dt;if(spawnTimer<=0){pattern();spawnTimer=Math.max(.35,.9-time*.0025)}if(bossMeter>=100)bossStart();for(let i=os.length-1;i>=0;i--){const o=os[i];o.x-=speed*dt;o.cool=Math.max(0,o.cool-dt);if(o.x<-150){os.splice(i,1);continue}if(!o.dead)collide(o)}updateBoss(dt,speed);for(const q of ps){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=650*dt;q.life-=dt}for(const q of texts){q.y-=30*dt;q.life-=dt}while(ps.length>220)ps.shift();hud()}
function hud(){$('health').textContent='●'.repeat(Math.max(0,health))+'○'.repeat(3-health);$('energyText').textContent=energy|0;$('score').textContent=score|0;$('combo').textContent='x'+combo.toFixed(1);$('gems').textContent=gems;$('energyBar').style.width=energy+'%';$('rageBar').style.width=rage+'%';$('bossBar').style.width=(boss?boss.hp/boss.max*100:bossMeter)+'%';$('bestScore').textContent=(+localStorage.getItem('DL_BEST')||0).toLocaleString()}
function draw(){x.save();if(shake>0){x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.86;if(shake<.2)shake=0}const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#07152b');g.addColorStop(1,'#13223a');x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle='#ffffff22';for(let i=0;i<45;i++)x.fillRect((i*83+time*12)%W,(i*47)%270,2,2);x.fillStyle='#10251b';x.fillRect(0,G,W,H-G);x.strokeStyle='#284733';for(const l of L){x.beginPath();x.moveTo(l-55,G);x.lineTo(l-160,H);x.stroke();x.beginPath();x.moveTo(l+55,G);x.lineTo(l+160,H);x.stroke()}
for(const o of os){if(o.dead)continue;x.save();x.translate(o.x,o.y);if(o.type==='gem'){x.fillStyle='#62eaff';x.beginPath();x.moveTo(0,-16);x.lineTo(13,0);x.lineTo(0,16);x.lineTo(-13,0);x.fill()}else if(o.type==='enemy'||o.type==='elite'){x.font=o.type==='elite'?'58px serif':'50px serif';x.textAlign='center';x.fillText(o.type==='elite'?'👹':'🦎',0,22)}else if(o.type==='air'){x.fillStyle='#ffbd68';x.fillRect(-28,-12,56,24)}else if(o.type==='trap'){x.fillStyle='#ff6478';x.beginPath();x.moveTo(-30,18);x.lineTo(0,-25);x.lineTo(30,18);x.fill()}else{x.fillStyle='#69788a';x.fillRect(-27,-25,54,50)}x.restore()}
if(boss){x.font='76px serif';x.textAlign='center';x.fillText('👑',boss.x,G-80);x.fillStyle='#401526';x.fillRect(boss.x-70,G-150,140,7);x.fillStyle='#ff6478';x.fillRect(boss.x-70,G-150,140*boss.hp/boss.max,7)}x.save();x.translate(p.x,G-p.y-45);x.font='72px serif';x.textAlign='center';x.fillText('🦖',0,28);if(p.parry>0){x.strokeStyle='#9c8cff';x.lineWidth=6;x.beginPath();x.arc(0,-5,58,0,Math.PI*2);x.stroke()}if(p.attack>0){x.strokeStyle='#fff';x.lineWidth=7;x.beginPath();x.arc(35,-20,52,-1.2,1.2);x.stroke()}x.restore();for(const q of ps){x.globalAlpha=Math.max(0,q.life);x.fillStyle=q.k==='red'?'#ff6478':q.k==='violet'?'#9c8cff':q.k==='gold'?'#ffbd68':'#62eaff';x.fillRect(q.x,q.y,q.size,q.size)}x.globalAlpha=1;for(const q of texts){x.globalAlpha=Math.max(0,q.life);x.font='900 16px Arial';x.textAlign='center';x.fillStyle=q.k==='red'?'#ff6478':q.k==='gold'||q.k==='boss'?'#ffbd68':'#62eaff';x.fillText(q.v,q.x,q.y)}x.globalAlpha=1;x.restore()}
function loop(now){const dt=Math.min(.032,(now-last)/1000||0);last=now;if(running&&!paused)update(dt);draw();requestAnimationFrame(loop)}hud();requestAnimationFrame(loop);
})();