(()=>{
'use strict';
const KEY='DINO_LEGENDS_LEADERBOARD_V2',PROFILE='DINO_LEGENDS_PROFILE_V2',SEASON='S1';
const API=(window.DINO_LEADERBOARD_API||'').replace(/\/$/,'');
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
let board=load(KEY,[]),profile=load(PROFILE,{id:'',name:'',title:'Rookie',tag:'',avatar:'🦖'});
const TITLES=['Rookie','Trailblazer','Gem Runner','Combo Master','Guardian Slayer','Apex Hunter','Dino Legend','Mythic Runner','Divine Apex'];
const AVATARS=['🦖','🐉','⚡','🔥','🌙','☄️','👑','💎','🦂','🐲'];
const clean=s=>String(s||'').replace(/[^a-zA-Z0-9 _-]/g,'').replace(/\s+/g,' ').trim().slice(0,16)||'Rookie Dino';
const cleanTag=s=>String(s||'').replace(/[^a-zA-Z0-9]/g,'').toUpperCase().slice(0,5);
const esc=s=>String(s||'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>{try{return crypto.randomUUID()}catch{return 'dino-'+Date.now()+'-'+Math.random().toString(36).slice(2)}};
function bestScore(){try{return Number((JSON.parse(localStorage.getItem('DINO_LEGENDS_V30')||'{}').best)||0)}catch{return 0}}
function rank(score){return ['ROOKIE','HUNTER','ELITE','APEX','LEGEND','MYTHIC','DIVINE','ASCENDANT'][Math.min(7,Math.floor(Number(score||0)/10000))]}
function save(){localStorage.setItem(KEY,JSON.stringify(board.slice(0,200)));localStorage.setItem(PROFILE,JSON.stringify(profile))}
async function onlineSubmit(entry){if(!API)return {online:false};try{const r=await fetch(API+'/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...entry,season:SEASON})});if(!r.ok)throw Error('submit');return {online:true}}catch{return {online:false}}}
async function onlineLoad(){if(!API)return null;try{const r=await fetch(API+'/top?season='+encodeURIComponent(SEASON),{cache:'no-store'});if(!r.ok)throw Error('load');const d=await r.json();return Array.isArray(d)?d:(Array.isArray(d.entries)?d.entries:[])}catch{return null}}
function ensurePanel(){const tabs=document.querySelector('.tabs'),app=document.querySelector('.app');if(!tabs||!app)return false;if(!tabs.querySelector('[data-panel="leaderboard"]')){const b=document.createElement('button');b.className='tab';b.dataset.panel='leaderboard';b.type='button';b.textContent='LEADERBOARD';tabs.insertBefore(b,tabs.querySelector('[data-panel="redeem"]')||null);b.onclick=show}if(!document.getElementById('leaderboard')){const s=document.createElement('section');s.className='panel';s.id='leaderboard';const r=document.getElementById('redeem');app.insertBefore(s,r||null)}return true}
function show(){ensurePanel();document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.panel==='leaderboard'));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='leaderboard'));render()}
async function render(){if(!ensurePanel())return;const p=document.getElementById('leaderboard');const best=bestScore();const online=await onlineLoad();if(online){board=online.map(x=>({id:String(x.id||''),name:clean(x.name),score:Number(x.score)||0,title:String(x.title||rank(x.score)),tag:cleanTag(x.tag),avatar:x.avatar||'🦖'})).sort((a,b)=>b.score-a.score).slice(0,100)}const rows=[...board].sort((a,b)=>b.score-a.score).slice(0,50);const mine=rows.findIndex(x=>x.id===profile.id);p.innerHTML=`<div class="heading"><div><small>GLOBAL HALL · SEASON ${SEASON}</small><h2>WORLD LEADERBOARD</h2></div><b>${rank(best)}</b></div><div class="leaderProfile"><div class="namePreview">${esc(profile.avatar||'🦖')}</div><label>PLAYER NAME<input id="playerName" maxlength="16" value="${esc(profile.name)}" placeholder="YOUR LEGEND NAME"></label><label>TITLE<select id="playerTitle">${TITLES.map(x=>`<option ${x===profile.title?'selected':''}>${x}</option>`).join('')}</select></label><label>TAG<input id="playerTag" maxlength="5" value="${esc(profile.tag)}" placeholder="DINO"></label><label>AVATAR<select id="playerAvatar">${AVATARS.map(x=>`<option ${x===profile.avatar?'selected':''}>${x}</option>`).join('')}</select></label><button class="action" id="saveName" type="button">SAVE PROFILE</button><span>BEST <strong>${best.toLocaleString()}</strong></span></div><div class="leaderStatus">${API?'<b>● GLOBAL SERVER</b> · Scores sync online':'<b>● LOCAL MODE</b> · Global server endpoint not configured yet'}</div><div class="leaderTable"><div class="leaderRow head"><i>#</i><b>LEGEND</b><b>SCORE</b><b>RANK</b></div>${rows.map((x,i)=>`<div class="leaderRow ${x.id===profile.id?'me':''}"><i>${i+1}</i><b>${esc(x.avatar||'🦖')} ${esc(x.name)} ${x.tag?`<small>#${esc(x.tag)}</small>`:''}<em>${esc(x.title||rank(x.score))}</em></b><b>${Number(x.score).toLocaleString()}</b><span>${rank(x.score)}</span></div>`).join('')||'<p class="empty">PLAY A RUN TO ENTER THE HALL.</p>'}</div><button class="action" id="submitScore" type="button">SUBMIT MY BEST SCORE</button>${mine>=0?`<small class="yourRank">YOUR POSITION · #${mine+1}</small>`:''}`;
document.getElementById('saveName').onclick=()=>{profile.name=clean(document.getElementById('playerName').value);profile.title=document.getElementById('playerTitle').value;profile.tag=cleanTag(document.getElementById('playerTag').value);profile.avatar=document.getElementById('playerAvatar').value;profile.id=profile.id||uid();save();render()};
document.getElementById('submitScore').onclick=async()=>{profile.name=clean(document.getElementById('playerName').value);profile.title=document.getElementById('playerTitle').value;profile.tag=cleanTag(document.getElementById('playerTag').value);profile.avatar=document.getElementById('playerAvatar').value;profile.id=profile.id||uid();const score=bestScore();const entry={id:profile.id,name:profile.name,score,title:profile.title,tag:profile.tag,avatar:profile.avatar};const old=board.find(x=>x.id===profile.id);if(old){old.score=Math.max(old.score,score);Object.assign(old,profile)}else board.push(entry);save();const result=await onlineSubmit(entry);const status=document.querySelector('.leaderStatus');if(status)status.innerHTML=result.online?'<b>● GLOBAL SERVER</b> · Score submitted worldwide':'<b>● LOCAL MODE</b> · Saved on this device';render()};}
function boot(){if(!ensurePanel())return;render();document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.panel==='leaderboard')show()}));document.addEventListener('dino-score-finished',render)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
