(()=>{
'use strict';
const SAVE='DINO_LEGENDS_V30', BP='DINO_BP_V1', M='DINO_MASTERY_V1', LOOT='DINO_LOOT_V1';
const load=()=>{try{return JSON.parse(localStorage.getItem(SAVE)||'{}')}catch{return {}}};
const save=s=>localStorage.setItem(SAVE,JSON.stringify(s));
const read=(k,d)=>{try{return {...d,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return {...d}}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const bpRewards=[['+1,000 GEMS',1000],['RELIC SHARD',1],['+2,500 GEMS',2500],['LOOT CHEST',1],['+5,000 GEMS',5000],['MASTER TOKEN',1],['+10,000 GEMS',10000],['LEGENDARY CHEST',1],['+25,000 GEMS',25000],['APEX CACHE',1]];
const masteryNames=['ROOKIE REX','VOID REX','GALAXY REX','EMBER REX','FROST REX','SHADOW REX'];
const lootNames=['COMMON RELIC','RARE RELIC','EPIC RELIC','LEGENDARY RELIC','APEX RELIC'];
function ensure(){const s=load();s.stats=s.stats||{};const bp=read(BP,{xp:0,claimed:[]}),mastery=read(M,{xp:0,level:1,claimed:[]}),loot=read(LOOT,{chests:0,relics:[],shards:0});return {s,bp,mastery,loot}}
function awardGems(n){const s=load();s.gems=(Number(s.gems)||0)+n;s.stats=s.stats||{};s.stats.gems=Math.max(Number(s.stats.gems)||0,s.gems);save(s)}
function addXP(n){const {bp,mastery}=ensure();bp.xp+=n;mastery.xp+=Math.round(n*.7);bp.level=Math.min(10,Math.floor(bp.xp/1000)+1);mastery.level=Math.min(20,Math.floor(mastery.xp/750)+1);write(BP,bp);write(M,mastery);render()}
function openChest(kind='LOOT CHEST'){const l=read(LOOT,{chests:0,relics:[],shards:0});const rarity=Math.min(4,Math.floor(Math.random()*5)+(kind==='LEGENDARY CHEST'?1:kind==='APEX CACHE'?2:0));const relic=lootNames[Math.min(4,rarity)];l.chests=Math.max(0,l.chests-1);l.relics.push({name:relic,rarity:rarity+1,at:Date.now()});l.shards+=rarity>=3?3:1;write(LOOT,l);const s=load();s.stats=s.stats||{};s.stats.relic=Math.max(Number(s.stats.relic)||0,l.relics.length);save(s);render();return relic}
function claimBP(i){const {bp}=ensure();if(i>=bp.level||bp.claimed.includes(i))return;bp.claimed.push(i);write(BP,bp);const reward=bpRewards[i];if(reward[1]&&reward[0].includes('GEMS'))awardGems(reward[1]);else {const l=read(LOOT,{chests:0,relics:[],shards:0});if(reward[0].includes('CHEST')||reward[0].includes('CACHE'))l.chests++;else l.shards++;write(LOOT,l)}render()}
function render(){const p=document.getElementById('progression');if(!p)return;const {s,bp,mastery,loot}=ensure();const bpPct=Math.min(100,bp.xp/10000*100),mPct=Math.min(100,(mastery.xp%750)/750*100);p.innerHTML=`<div class="heading"><div><small>SEASON 01 · PROGRESSION</small><h2>APEX PASS</h2></div><b>LV ${bp.level}/10</b></div><div class="featureGrid"><article class="featureCard"><small>BATTLE PASS</small><h3>SEASON 01</h3><div class="xpbar"><i style="width:${bpPct}%"></i></div><p>${bp.xp.toLocaleString()} / 10,000 XP</p><div class="rewardGrid">${bpRewards.map((r,i)=>`<button class="reward ${i<bp.level?'ready':''} ${bp.claimed.includes(i)?'claimed':''}" data-bp="${i}"><b>${i+1}</b><span>${r[0]}</span>${bp.claimed.includes(i)?'✓':''}</button>`).join('')}</div></article><article class="featureCard"><small>DINO MASTERY</small><h3>${masteryNames[(mastery.level-1)%masteryNames.length]}</h3><strong>LEVEL ${mastery.level}/20</strong><div class="xpbar"><i style="width:${mPct}%"></i></div><p>Earn Mastery XP by surviving, fighting and collecting.</p><ul class="cleanList"><li>Current XP: ${mastery.xp.toLocaleString()}</li><li>Mastery bonus: +${Math.max(0,mastery.level-1)}%</li><li>Next unlock: Level ${Math.min(20,mastery.level+1)}</li></ul></article><article class="featureCard"><small>LOOT & RELICS</small><h3>APEX VAULT</h3><strong>${loot.chests} CHESTS · ${loot.relics.length} RELICS</strong><p>Open earned chests for rarity-based relics.</p><button class="primary" id="openChest" ${loot.chests?'':'disabled'}>OPEN CHEST</button><p>Relic shards: ${loot.shards}</p></article><article class="featureCard"><small>BOSS RUSH</small><h3>GUARDIAN GAUNTLET</h3><p>Chain Guardian encounters. Each win raises the reward multiplier.</p><div class="rushStats"><b>BEST WAVE ${Number(s.stats?.bossRush||0)}</b><b>MULTI ×${Math.max(1,1+Math.floor(Number(s.stats?.bossRush||0)/3))}</b></div><button class="primary" id="bossRush">START BOSS RUSH</button></article></div><div class="heading compact"><div><small>LEADERBOARD</small><h2>GLOBAL RANKING</h2></div><b>ONLINE READY</b></div><div class="leaderWrap"><div id="globalBoard"></div><small>Online mode uses DINO_LEADERBOARD_ENDPOINT when configured; without a server the game safely falls back to local ranking.</small></div>`;
 p.querySelectorAll('[data-bp]').forEach(b=>b.onclick=()=>claimBP(Number(b.dataset.bp)));p.querySelector('#openChest')?.addEventListener('click',()=>{const l=read(LOOT,{chests:0,relics:[],shards:0});if(l.chests){const r=openChest();alert('FOUND · '+r)}});p.querySelector('#bossRush')?.addEventListener('click',()=>startBossRush());renderBoard();}
function startBossRush(){const s=load();s.stats=s.stats||{};s.stats.bossRush=Math.max(Number(s.stats.bossRush)||0,1);save(s);alert('BOSS RUSH READY · Defeat Guardians in sequence during your next run.');addXP(250)}
async function renderBoard(){const el=document.getElementById('globalBoard');if(!el)return;const s=load(),name=localStorage.getItem('DINO_PLAYER_NAME')||'ANONYMOUS DINO',score=Number(s.best)||0;const local=JSON.parse(localStorage.getItem('DINO_LOCAL_BOARD')||'[]');const me={name,score};const merged=[...local.filter(x=>x.name!==name),me].sort((a,b)=>b.score-a.score).slice(0,10);localStorage.setItem('DINO_LOCAL_BOARD',JSON.stringify(merged));let rows=merged;if(window.DINO_LEADERBOARD_ENDPOINT){try{const r=await fetch(window.DINO_LEADERBOARD_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(me)});if(r.ok){const data=await r.json();if(Array.isArray(data))rows=data.sort((a,b)=>b.score-a.score).slice(0,10)}}catch{}}el.innerHTML=`<div class="board">${rows.map((x,i)=>`<div><b>#${i+1}</b><span>${String(x.name||'DINO').slice(0,18)}</span><strong>${Number(x.score||0).toLocaleString()}</strong></div>`).join('')}</div>`}
window.DinoProgression={addXP,openChest,refresh:render};
const oldStart=window.startGame;if(oldStart)window.startGame=()=>{oldStart();addXP(100)};
function boot(){render();setInterval(()=>{const s=load();if(Number(s.stats?.runs)>0)addXP(10)},30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();