/* DINO LEGENDS V41 — TRUE SKIN IDENTITY SYSTEM */
(()=>{
  const R=[];
  const archetypes=[
    ['EMBER','🔥','flame','fire','#ff6b35','Blaze Dash'],['FROST','❄️','ice','ice','#62ecff','Frost Step'],['VOID','🌌','void','void','#b968ff','Void Blink'],['FOREST','🌿','leaf','nature','#55e58c','Vine Guard'],['CYBER','⚡','cyber','electric','#27d9ff','Overclock'],['SHADOW','🌑','shadow','shadow','#c16cff','Night Cloak'],['SOLAR','☀️','solar','light','#ffe36e','Solar Burst'],['TOXIC','☣️','toxic','poison','#9cff4d','Toxic Trail'],['STORM','🌩️','storm','storm','#a9b8ff','Thunder Rush'],['CRYSTAL','💎','crystal','crystal','#ff7de3','Prism Shield']
  ];
  const names=['Rex','Raptor','Drake','Titan','Wyvern','Goliath','Saurian','Beast','Warden','Emperor'];
  for(let i=0;i<100;i++){
    const a=archetypes[i%10], tier=Math.floor(i/10)+1;
    R.push({id:i,name:`${a[0]} ${names[(i*7)%10]} ${tier}`,icon:a[1],style:a[2],element:a[3],color:a[4],ability:a[5],tier, rarity:tier>=9?'DIVINE':tier>=7?'MYTHIC':tier>=5?'LEGENDARY':tier>=3?'EPIC':'RARE',speed:1+(i%5)*.04,jump:1+((i*3)%5)*.035,shield:1+((i*7)%4)*.06,magnet:1+((i*11)%5)*.05,trail:i%6,scale:.88+(i%7)*.035,price:(window.skins?.[i]?.[2])||0});
  }
  window.DINO_SKIN_VARIANTS=R;
  const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function v(){return R[window.save?.skin||0]||R[0]}
  function avatarMarkup(s,small=false){return `<div class="skinAvatar skin-${s.style}" style="--skin:${s.color};--scale:${s.scale}"><span class="skinAura"></span><span class="skinTrail"></span><span class="skinBody">🦖</span><b class="skinIcon">${s.icon}</b><em>${s.element}</em></div>`}
  window.renderAvatar=()=>{const s=v(); if($('avatar'))$('avatar').innerHTML=avatarMarkup(s); if($('startAvatar'))$('startAvatar').innerHTML=avatarMarkup(s,true); document.body.dataset.skin=s.style;};
  window.renderSkins=()=>{const g=$('skinGrid');if(!g)return;g.innerHTML=R.map(s=>{const owned=window.save.owned.includes(s.id),active=window.save.skin===s.id;return `<article class="item skinItem skin-${s.style}" style="--glow:${s.color}"><div class="skinPreview">${avatarMarkup(s)}</div><div class="skinMeta"><span class="rarity">${s.rarity}</span><span class="tier">TIER ${s.tier}</span></div><h3>${esc(s.name)}</h3><small>${esc(s.element.toUpperCase())} • ${esc(s.ability)}</small><div class="skinStats"><span>⚡ ${Math.round(s.speed*100)}%</span><span>⬆ ${Math.round(s.jump*100)}%</span><span>🛡 ${Math.round(s.shield*100)}%</span><span>💎 ${Math.round(s.magnet*100)}%</span></div><p>Unique aura • trail • silhouette • ability • stat profile</p><footer><span class="price">${active?'EQUIPPED':owned?'OWNED':((window.skins?.[s.id]?.[2]||s.price).toLocaleString()+' 💎')}</span><button class="action skinAction" data-skin="${s.id}" ${(!owned&&!active&&window.save.gems<(window.skins?.[s.id]?.[2]||s.price))?'disabled':''}>${active?'EQUIPPED':owned?'EQUIP':'BUY'}</button></footer></article>`}).join('');g.querySelectorAll('.skinAction').forEach(b=>b.onclick=()=>window.skin(+b.dataset.skin));$('skinCount').textContent=`${window.save.owned.length} / 100`;};
  const style=document.createElement('style');style.textContent=`
  .skinItem{overflow:hidden;position:relative}.skinPreview{height:150px;display:grid;place-items:center;border-radius:18px;background:radial-gradient(circle at 50% 55%,color-mix(in srgb,var(--glow) 24%,transparent),transparent 58%),#ffffff04;margin-bottom:12px}.skinAvatar{position:relative;width:105px;height:105px;display:grid;place-items:center;transform:scale(var(--scale));filter:drop-shadow(0 0 18px var(--skin))}.skinBody{font-size:74px;z-index:3;filter:saturate(1.25)}.skinIcon{position:absolute;right:5px;top:2px;font-size:26px;z-index:5}.skinAvatar em{position:absolute;bottom:3px;font:700 7px Orbitron;letter-spacing:1px;color:var(--skin);z-index:5}.skinAura{position:absolute;width:92px;height:92px;border:2px solid var(--skin);border-radius:42% 58% 52% 48%;box-shadow:0 0 24px var(--skin),inset 0 0 22px var(--skin);opacity:.65;animation:skinPulse 1.8s ease-in-out infinite}.skinTrail{position:absolute;width:125px;height:35px;bottom:9px;left:-10px;border-radius:50%;background:var(--skin);filter:blur(16px);opacity:.25}.skin-fire .skinAura{border-radius:45% 55% 65% 35%;animation:skinFire .55s infinite alternate}.skin-ice .skinAura{transform:rotate(45deg);border-radius:12px}.skin-void .skinAura{border-style:dashed;animation:skinSpin 4s linear infinite}.skin-cyber .skinAura{border-radius:8px;box-shadow:0 0 12px var(--skin),0 0 30px var(--skin)}.skin-shadow .skinAura{filter:blur(2px);opacity:.9}.skin-toxic .skinTrail{animation:toxic 1s infinite}.skin-storm .skinAura{clip-path:polygon(50% 0,60% 38%,100% 45%,64% 57%,72% 100%,50% 68%,25% 100%,34% 58%,0 46%,39% 37%)}.skin-crystal .skinAura{clip-path:polygon(50% 0,90% 25%,80% 80%,50% 100%,20% 80%,10% 25%)}.skin-solar .skinAura{border-width:4px;box-shadow:0 0 35px var(--skin)}.skin-forest .skinTrail{height:55px;border-radius:45% 55% 20% 80%}.skinMeta,.skinStats{display:flex;justify-content:space-between;gap:6px}.rarity,.tier{font:700 7px Orbitron;letter-spacing:.8px;color:var(--glow);padding:5px 7px;border:1px solid color-mix(in srgb,var(--glow) 35%,transparent);border-radius:999px}.skinStats{margin:12px 0;font:700 8px Orbitron;color:#bbb}.skinItem p{min-height:30px}.skinItem h3{font-size:13px}.skinItem small{font:700 8px Orbitron;color:#aaa}.skinItem .price{font:700 9px Orbitron}.skinItem:after{content:'';position:absolute;inset:auto -30% -45% -30%;height:90px;background:var(--glow);filter:blur(55px);opacity:.12;pointer-events:none}@keyframes skinPulse{50%{transform:scale(1.08);opacity:.95}}@keyframes skinFire{to{transform:scale(1.14) rotate(3deg);filter:drop-shadow(0 0 28px var(--skin))}}@keyframes skinSpin{to{transform:rotate(360deg)}}@keyframes toxic{50%{transform:translateX(12px) scaleX(.8)}}
  `;document.head.appendChild(style);
  function boot(){if(window.renderAvatar)window.renderAvatar();if(window.renderSkins)window.renderSkins();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,50));else setTimeout(boot,50);
})();
